set(SDL_MIXER_ROOT ${CMAKE_BINARY_DIR}/SDL_mixer)
set(SDL_ROOT ${CMAKE_BINARY_DIR}/SDL)
set(SDL3_INCLUDE_DIR ${CMAKE_BINARY_DIR}/SDL/include/SDL3)

if(PLAT_MINGW_X86_64)
    set(SDL_MIXER_C_FLAGS "-fno-stack-protector")
    set(SDL_MIXER_CXX_FLAGS "-fno-stack-protector")
elseif(PLAT_MINGW_X86_32)
    set(SDL_MIXER_C_FLAGS "-fno-stack-protector")
    set(SDL_MIXER_CXX_FLAGS "-fno-stack-protector")
else()
    set(SDL_MIXER_C_FLAGS "")
    set(SDL_MIXER_CXX_FLAGS "")
endif()

if(TARGET_ANDROID)
set(SDL_MIXER_BUILD_SHARED_LIBS TRUE)
else()
set(SDL_MIXER_BUILD_SHARED_LIBS FALSE)
endif()

# *Replicate* variables generated by `FindSDL_mixer`
set(SDL_MIXER_FOUND TRUE)
set(SDL_MIXER_INCLUDE_DIRS ${SDL_MIXER_ROOT}/include/SDL3_mixer)
if(PLAT_MSVC)
    set(SDL_MIXER_LIBRARIES "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_mixer-static${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
    if(SDL_MIXER_BUILD_SHARED_LIBS)
        set(SDL_MIXER_LIBRARIES "${SDL_MIXER_ROOT}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}SDL3_mixer${CMAKE_SHARED_LIBRARY_SUFFIX}")
    else()
        set(SDL_MIXER_LIBRARIES "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_mixer${CMAKE_STATIC_LIBRARY_SUFFIX}")
    endif()
endif()
# TODO: Not sure why SDL_mixer doesn't do link these into SDL_mixer.a?

if(PLAT_MSVC)
    set(SDL_MIXER_DEPS  "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}vorbisfile${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}vorbis${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}ogg${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}opusfile${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}opus${CMAKE_STATIC_LIBRARY_SUFFIX}"
    )
elseif(TARGET_ANDROID)
    set(SDL_MIXER_DEPS  SDL::SDL) # ????
else()
    set(SDL_MIXER_DEPS  SDL::SDL
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}vorbisfile${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}vorbis${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}ogg${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}opusfile${CMAKE_STATIC_LIBRARY_SUFFIX}"
                        "${SDL_MIXER_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}opus${CMAKE_STATIC_LIBRARY_SUFFIX}"
    )
endif()

if(PLAT_MSVC)
    set(SDL_MIXER_PATCH_COMMAND git submodule update --init)
else()
    # Run through `bash -c` so the &&/|| operators are honoured -- ExternalProject
    # executes PATCH_COMMAND without a shell, so an unwrapped `cd ... && ...` would
    # try to exec `cd` with the rest as literal args. Every step is best-effort: on
    # a flatpak build the build sandbox has no network (download.sh can't fetch) and
    # incremental re-runs would re-apply the patch -- neither should fail the build,
    # since the ogg/vorbis submodules are already checked out by the source fetch.
    # No ';' in the command: CMake would treat semicolons as list-element separators
    # and hand them to bash as separate args. Use subshells + &&/|| instead, with a
    # trailing `|| true` so the whole step always succeeds.
    #
    # SDL3_mixer's own CMakeLists tries to fold every vendored codec (ogg, vorbis,
    # opus, ...) into ONE unified export set (SDL3MixerTargets) for find_package()
    # consumers, but several of those vendored subprojects (ogg in particular) also
    # do their OWN install(TARGETS ... EXPORT ...) as standalone projects, and a
    # CMake target can't belong to two export sets -- so combining them errors out
    # at the Generate step. We never consume SDL3_mixer via find_package() (this
    # project reads the built static libs directly by path), so
    # patch_sdl_mixer_cmakelists.py strips that unused package/export machinery
    # while leaving the plain install(TARGETS ...) file-copying in place -- see
    # that script for the full rationale.
    set(SDL_MIXER_PATCH_COMMAND bash -c "cd '${CMAKE_SOURCE_DIR}/lib/SDL_mixer/external/ogg' && ( git apply '${PROJECT_SOURCE_DIR}/lib/ogg_fix.patch' || true ) && cd '${CMAKE_SOURCE_DIR}/lib/SDL_mixer' && ( python3 '${PROJECT_SOURCE_DIR}/cmake_modules/patch_sdl_mixer_cmakelists.py' CMakeLists.txt || true ) && chmod +x external/download.sh && ( ./external/download.sh || true ) || true")
endif()

ExternalProject_Add(
    SDL_mixer
    SOURCE_DIR          ${CMAKE_SOURCE_DIR}/lib/SDL_mixer
    BINARY_DIR          ${SDL_MIXER_ROOT}
    INSTALL_DIR         ${SDL_MIXER_ROOT}
    UPDATE_DISCONNECTED TRUE
    PATCH_COMMAND       ${SDL_MIXER_PATCH_COMMAND}
    CMAKE_ARGS          --toolchain ${CMAKE_TOOLCHAIN_FILE}
                        --install-prefix ${SDL_MIXER_ROOT} -DCMAKE_INSTALL_LIBDIR=lib
                        -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
                        -DCMAKE_C_FLAGS:STRING=${SDL_MIXER_C_FLAGS}
                        -DCMAKE_CXX_FLAGS:STRING=${SDL_MIXER_CXX_FLAGS}
                        -DCMAKE_BUILD_TYPE:STRING=Release
                        -DBUILD_SHARED_LIBS:BOOL=${SDL_MIXER_BUILD_SHARED_LIBS}
                        -DSDLMIXER_MOD:BOOL=FALSE
                        -DSDLMIXER_MIDI:BOOL=FALSE
                        # GME (game console chiptune formats) is enabled by default and
                        # new vs. the old 2.6.3 backend list, but nothing in the engine
                        # loads that format (only .ogg music) and its libgme.a isn't in
                        # our SDL_MIXER_DEPS link list -- disable rather than add a link
                        # dependency for a codec we never use.
                        -DSDLMIXER_GME:BOOL=FALSE
                        # mpg123 backend's vendored fork has a broken include path (its
                        # decoder can't find fmt123.h when consumed as a static lib) --
                        # not worth chasing since the engine never loads MP3 (only .ogg
                        # music); drmp3 (header-only, no vendored dep) stays enabled as
                        # the default MP3 decoder if ever needed.
                        -DSDLMIXER_MP3_MPG123:BOOL=FALSE
                        -DSDLMIXER_DEPS_SHARED:BOOL=FALSE
                        -DSDLMIXER_EXAMPLES:BOOL=FALSE
                        # test/ (testaudiodecoder, testspatialization, testmixer) builds by
                        # default too (separate option from EXAMPLES) and we don't need it either;
                        # on mingw it also hard-fails the whole build (Homebrew's mingw-w64 links
                        # both libssp.a and libssp.dll.a, giving a duplicate __stack_chk_fail
                        # definition) -- disable rather than chase a toolchain packaging bug in
                        # code we never run.
                        -DSDLMIXER_TESTS:BOOL=FALSE
                        -DSDLMIXER_VENDORED:BOOL=TRUE
                        -DSDLMIXER_FLAC:BOOL=FALSE
                        -DSDLMIXER_OPUS:BOOL=TRUE
                        -DSDLMIXER_VORBIS_STB:BOOL=FALSE
                        -DSDLMIXER_VORBIS_VORBISFILE:BOOL=TRUE
                        -DSDLMIXER_VORBIS_TREMOR:BOOL=FALSE
                        -DSDLMIXER_VORBIS_VORBISFILE_SHARED:BOOL=FALSE
                        -DSDLMIXER_OPUS_SHARED:BOOL=FALSE
                        -DSDLMIXER_WAVPACK:BOOL=FALSE
                        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
                        -DCMAKE_INSTALL_LIBDIR=lib
                        # SDL_mixer sets this as a plain (non-cache) var before add_subdirectory(external/ogg),
                        # but vendored ogg's own option(INSTALL_CMAKE_PACKAGE_MODULE ... ON) still wins unless
                        # it's pre-seeded as a real CACHE entry here -- otherwise ogg self-exports as OggTargets
                        # AND gets pulled into SDL3_mixer's own export set, which CMake refuses (target exported
                        # under two different export sets).
                        -DINSTALL_CMAKE_PACKAGE_MODULE:BOOL=FALSE
    CMAKE_CACHE_ARGS
                        -DCMAKE_PREFIX_PATH:PATH=${SDL_ROOT}
                        -DSDL3_DIR:PATH=${SDL_ROOT}/lib/cmake/SDL3

    DEPENDS             SDL::SDL
    BUILD_BYPRODUCTS    ${SDL_MIXER_LIBRARIES} ${SDL_MIXER_DEPS}
)

set(SDL_MIXER_VERSION 3.2.4)
string(REGEX MATCH "^[0-9]+" SDL_MIXER_VERSION_MAJOR ${SDL_MIXER_VERSION})
string(REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" SDL_MIXER_VERSION_MINOR ${SDL_MIXER_VERSION})
string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" SDL_MIXER_VERSION_PATCH ${SDL_MIXER_VERSION})
message(SDL_MIXER_VERSION_MAJOR\ ==\ ${SDL_MIXER_VERSION_MAJOR})
message(SDL_MIXER_VERSION_MINOR\ ==\ ${SDL_MIXER_VERSION_MINOR})
message(SDL_MIXER_VERSION_PATCH\ ==\ ${SDL_MIXER_VERSION_PATCH})
# *Replicate* SDL target
if(NOT TARGET SDL::Mixer)
    if(TARGET_ANDROID)
        add_library(SDL::Mixer SHARED IMPORTED)
    else()
        add_library(SDL::Mixer STATIC IMPORTED)
    endif()
endif()
add_dependencies(SDL::Mixer SDL_mixer)
file(MAKE_DIRECTORY ${SDL_MIXER_INCLUDE_DIRS})
set_target_properties(
    SDL::Mixer PROPERTIES
    IMPORTED_LOCATION ${SDL_MIXER_LIBRARIES}
    IMPORTED_IMPLIB ${SDL_MIXER_LIBRARIES}
)
target_include_directories(SDL::Mixer INTERFACE ${SDL_MIXER_INCLUDE_DIRS})
target_link_directories(SDL::Mixer INTERFACE ${SDL_MIXER_ROOT}/lib)
