# CMake toolchain file
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION "0.0.0")
set(CMAKE_SYSTEM_PROCESSOR arm)

if(DEFINED ENV{DEVKITPRO})
    set(DEVKITPRO $ENV{DEVKITPRO})
else()
    set(DEVKITPRO /opt/devkitpro)
endif()

if(DEFINED ENV{DEVKITARM})
    set(DEVKITARM $ENV{DEVKITARM})
else()
    set(DEVKITARM ${DEVKITPRO}/devkitARM)
endif()

if(DEFINED ENV{NDSTOOL})
    set(NDSTOOL $ENV{NDSTOOL})
else()
    set(NDSTOOL ${DEVKITPRO}/tools/bin/ndstool)
endif()

if(DEFINED ENV{LIBNDS})
    set(LIBNDS $ENV{LIBNDS})
else()
    set(LIBNDS ${DEVKITPRO}/libnds)
endif()

set(TOOLCHAIN_PREFIX arm-none-eabi)
set(TOOLCHAIN_PREFIX_PATH ${DEVKITARM}/bin/${TOOLCHAIN_PREFIX})

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PREFIX_PATH}-gcc" CACHE STRING "C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX_PATH}-g++" CACHE STRING "C++ compiler" FORCE)

set(CMAKE_C_FLAGS_INIT "")
set(CMAKE_CXX_FLAGS_INIT ${CMAKE_C_FLAGS_INIT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PLAT_TWL TRUE)

message( STATUS "Nintendo DSi ARM32 toolchain invoked" )