set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_C_COMPILER   "emcc" CACHE STRING "C compiler" FORCE)
set(CMAKE_CXX_COMPILER "em++" CACHE STRING "C++ compiler" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PLAT_WASM TRUE)
set(SDL2_MIXER_INCLUDE_DIR "")

message( STATUS "Emscripten toolchain invoked" )
