#include "sithCogThing.h"

#include <stdint.h>

static void (*sithCogThing_GetThingType)(sithCog* ctx) = (void*)0x00502080;
static void (*sithCogThing_CreateThing)(sithCog* ctx) = (void*)0x005020B0;
static void (*sithCogThing_CreateThingNr)(sithCog* ctx) = (void*)0x00502150;
static void (*sithCogThing_createThingUnused)(sithCog* ctx) = (void*)0x005021F0;
static void (*sithCogThing_CreateThingAtPos)(sithCog* ctx) = (void*)0x00502290;
static void (*sithCogThing_CreateThingAtPosNr)(sithCog* ctx) = (void*)0x005022A0;
static void (*sithCogThing_createThingAtPos_nr)(sithCog* ctx) = (void*)0x005022B0;
static void (*sithCogThing_DamageThing)(sithCog* ctx) = (void*)0x00502430;
static void (*sithCogThing_HealThing)(sithCog* ctx) = (void*)0x00502500;
static void (*sithCogThing_GetThingHealth)(sithCog* ctx) = (void*)0x00502570;
static void (*sithCogThing_SetHealth)(sithCog* ctx) = (void*)0x005025C0;
static void (*sithCogThing_DestroyThing)(sithCog* ctx) = (void*)0x00502600;
static void (*sithCogThing_JumpToFrame)(sithCog* ctx) = (void*)0x00502650;
static void (*sithCogThing_MoveToFrame)(sithCog* ctx) = (void*)0x00502720;
static void (*sithCogThing_SkipToFrame)(sithCog* ctx) = (void*)0x005027D0;
static void (*sithCogThing_RotatePivot)(sithCog* ctx) = (void*)0x00502880;
static void (*sithCogThing_Rotate)(sithCog* ctx) = (void*)0x00502950;
static void (*sithCogThing_GetThingLight)(sithCog* ctx) = (void*)0x00502990;
static void (*sithCogThing_SetThingLight)(sithCog* ctx) = (void*)0x005029D0;
static void (*sithCogThing_ThingLightAnim)(sithCog* ctx) = (void*)0x00502A60;
static void (*sithCogThing_WaitForStop)(sithCog* ctx) = (void*)0x00502B10;
static void (*sithCogThing_GetThingSector)(sithCog* ctx) = (void*)0x00502B80;
static void (*sithCogThing_GetCurFrame)(sithCog* ctx) = (void*)0x00502BC0;
static void (*sithCogThing_GetGoalFrame)(sithCog* ctx) = (void*)0x00502C00;
static void (*sithCogThing_StopThing)(sithCog* ctx) = (void*)0x00502C40;
static void (*sithCogThing_IsMoving)(sithCog* ctx) = (void*)0x00502CB0;
static void (*sithCogThing_SetThingPulse)(sithCog* ctx) = (void*)0x00502D60;
static void (*sithCogThing_SetThingTimer)(sithCog* ctx) = (void*)0x00502DD0;
static void (*sithCogThing_CaptureThing)(sithCog* ctx) = (void*)0x00502E40;
static void (*sithCogThing_ReleaseThing)(sithCog* ctx) = (void*)0x00502E70;
static void (*sithCogThing_GetThingParent)(sithCog* ctx) = (void*)0x00502EB0;
static void (*sithCogThing_GetThingPos)(sithCog* ctx) = (void*)0x00502EF0;
static void (*sithCogThing_SetThingPos)(sithCog* ctx) = (void*)0x00502F30;
static void (*sithCogThing_GetInv)(sithCog* ctx) = (void*)0x00502FC0;
static void (*sithCogThing_SetInv)(sithCog* ctx) = (void*)0x00503020;
static void (*sithCogThing_ChangeInv)(sithCog* ctx) = (void*)0x00503080;
static void (*sithCogThing_GetInvCog)(sithCog* ctx) = (void*)0x005030F0;
static void (*sithCogThing_GetThingVel)(sithCog* ctx) = (void*)0x00503160;
static void (*sithCogThing_SetThingVel)(sithCog* ctx) = (void*)0x00503210;
static void (*sithCogThing_ApplyForce)(sithCog* ctx) = (void*)0x00503290;
static void (*sithCogThing_AddThingVel)(sithCog* ctx) = (void*)0x00503300;
static void (*sithCogThing_GetThingLvec)(sithCog* ctx) = (void*)0x00503390;
static void (*sithCogThing_GetThingUvec)(sithCog* ctx) = (void*)0x005033D0;
static void (*sithCogThing_GetThingRvec)(sithCog* ctx) = (void*)0x00503410;
static void (*sithCogThing_sub_503450)(sithCog* ctx) = (void*)0x00503450;
static void (*sithCogThing_DetachThing)(sithCog* ctx) = (void*)0x00503490;
static void (*sithCogThing_GetAttachFlags)(sithCog* ctx) = (void*)0x005034F0;
static void (*sithCogThing_AttachThingToSurf)(sithCog* ctx) = (void*)0x00503520;
static void (*sithCogThing_AttachThingToThing)(sithCog* ctx) = (void*)0x00503590;
static void (*sithCogThing_AttachThingToThingEx)(sithCog* ctx) = (void*)0x00503600;
static void (*sithCogThing_PlayMode)(sithCog* ctx) = (void*)0x00503680;
static void (*sithCogThing_PlayKey)(sithCog* ctx) = (void*)0x00503740;
static void (*sithCogThing_StopKey)(sithCog* ctx) = (void*)0x00503870;
static void (*sithCogThing_SetThingModel)(sithCog* ctx) = (void*)0x00503920;
static void (*sithCogThing_GetThingModel)(sithCog* ctx) = (void*)0x005039B0;
static void (*sithCogThing_SetArmedMode)(sithCog* ctx) = (void*)0x00503A00;
static void (*sithCogThing_GetThingFlags)(sithCog* ctx) = (void*)0x00503A70;
static void (*sithCogThing_SetThingFlags)(sithCog* ctx) = (void*)0x00503AA0;
static void (*sithCogThing_ClearThingFlags)(sithCog* ctx) = (void*)0x00503B00;
static void (*sithCogThing_TeleportThing)(sithCog* ctx) = (void*)0x00503B60;
static void (*sithCogThing_SetThingType)(sithCog* ctx) = (void*)0x00503C50;
static void (*sithCogThing_GetCollideType)(sithCog* ctx) = (void*)0x00503C80;
static void (*sithCogThing_SetCollideType)(sithCog* ctx) = (void*)0x00503CB0;
static void (*sithCogThing_FirstThingInSector)(sithCog* ctx) = (void*)0x00503D10;
static void (*sithCogThing_NextThingInSector)(sithCog* ctx) = (void*)0x00503D60;
static void (*sithCogThing_PrevThingInSector)(sithCog* ctx) = (void*)0x00503DA0;
static void (*sithCogThing_GetInvMin)(sithCog* ctx) = (void*)0x00503DE0;
static void (*sithCogThing_GetInvMax)(sithCog* ctx) = (void*)0x00503E40;
static void (*sithCogThing_sub_503EA0)(sithCog* ctx) = (void*)0x00503EA0;
static void (*sithCogThing_sub_503EE0)(sithCog* ctx) = (void*)0x00503EE0;
static void (*sithCogThing_sub_503F40)(sithCog* ctx) = (void*)0x00503F40;
static void (*sithCogThing_PathMovePause)(sithCog* ctx) = (void*)0x00503FA0;
static void (*sithCogThing_SetHeadlightIntensity)(sithCog* ctx) = (void*)0x00503FF0;
static void (*sithCogThing_GetHeadlightIntensity)(sithCog* ctx) = (void*)0x00504050;
static void (*sithCogThing_IsThingVisible)(sithCog* ctx) = (void*)0x005040A0;
static void (*sithCogThing_PathMoveResume)(sithCog* ctx) = (void*)0x005040E0;
static void (*sithCogThing_SetCurInvWeapon)(sithCog* ctx) = (void*)0x00504130;
static void (*sithCogThing_GetCurInvWeapon)(sithCog* ctx) = (void*)0x00504160;
static void (*sithCogThing_SetThingGeoMode)(sithCog* ctx) = (void*)0x005041A0;
static void (*sithCogThing_GetThingGeoMode)(sithCog* ctx) = (void*)0x005041D0;
static void (*sithCogThing_SetThingLightMode)(sithCog* ctx) = (void*)0x00504200;
static void (*sithCogThing_GetThingLightMode)(sithCog* ctx) = (void*)0x00504230;
static void (*sithCogThing_SetThingTexMode)(sithCog* ctx) = (void*)0x00504260;
static void (*sithCogThing_GetThingTexMode)(sithCog* ctx) = (void*)0x00504290;
static void (*sithCogThing_SetThingCurGeoMode)(sithCog* ctx) = (void*)0x005042C0;
static void (*sithCogThing_GetThingCurGeoMode)(sithCog* ctx) = (void*)0x00504320;
static void (*sithCogThing_SetThingCurLightmode)(sithCog* ctx) = (void*)0x00504350;
static void (*sithCogThing_GetThingCurLightMode)(sithCog* ctx) = (void*)0x00504380;
static void (*sithCogThing_SetThingCurTexMode)(sithCog* ctx) = (void*)0x005043B0;
static void (*sithCogThing_GetThingCurTexMode)(sithCog* ctx) = (void*)0x005043E0;
static void (*sithCogThing_SetActorExtraSpeed)(sithCog* ctx) = (void*)0x00504410;
static void (*sithCogThing_GetThingTemplate)(sithCog* ctx) = (void*)0x00504440;
static void (*sithCogThing_SetLifeLeft)(sithCog* ctx) = (void*)0x00504480;
static void (*sithCogThing_GetLifeLeft)(sithCog* ctx) = (void*)0x00504500;
static void (*sithCogThing_SetThingThrust)(sithCog* ctx) = (void*)0x00504540;
static void (*sithCogThing_GetThingThrust)(sithCog* ctx) = (void*)0x005045A0;
static void (*sithCogThing_AmputateJoint)(sithCog* ctx) = (void*)0x005045D0;
static void (*sithCogThing_SetActorWeapon)(sithCog* ctx) = (void*)0x00504620;
static void (*sithCogThing_GetActorWeapon)(sithCog* ctx) = (void*)0x00504680;
static void (*sithCogThing_GetPhysicsFlags)(sithCog* ctx) = (void*)0x005046F0;
static void (*sithCogThing_SetPhysicsFlags)(sithCog* ctx) = (void*)0x00504730;
static void (*sithCogThing_ClearPhysicsFlags)(sithCog* ctx) = (void*)0x005047A0;
static void (*sithCogThing_SkillTarget)(sithCog* ctx) = (void*)0x005047E0;
static void (*sithCogThing_ParseArg)(sithCog* ctx) = (void*)0x005048D0;
static void (*sithCogThing_SetThingRotVel)(sithCog* ctx) = (void*)0x00504950;
static void (*sithCogThing_GetThingRotVel)(sithCog* ctx) = (void*)0x005049D0;
static void (*sithCogThing_SetThingLook)(sithCog* ctx) = (void*)0x00504A10;
static void (*sithCogThing_IsCrouching)(sithCog* ctx) = (void*)0x00504A90;
static void (*sithCogThing_GetThingClassCog)(sithCog* ctx) = (void*)0x00504AE0;
static void (*sithCogThing_SetThingClassCog)(sithCog* ctx) = (void*)0x00504B20;
static void (*sithCogThing_GetThingCaptureCog)(sithCog* ctx) = (void*)0x00504B50;
static void (*sithCogThing_SetThingCaptureCog)(sithCog* ctx) = (void*)0x00504B90;
static void (*sithCogThing_GetThingRespawn)(sithCog* ctx) = (void*)0x00504BC0;
static void (*sithCogThing_GetThingSignature)(sithCog* ctx) = (void*)0x00504BF0;
static void (*sithCogThing_SetThingAttachFlags)(sithCog* ctx) = (void*)0x00504C20;
static void (*sithCogThing_ClearThingAttachFlags)(sithCog* ctx) = (void*)0x00504C80;
static void (*sithCogThing_GetParticleSize)(sithCog* ctx) = (void*)0x00504CE0;
static void (*sithCogThing_SetParticleSize)(sithCog* ctx) = (void*)0x00504D20;
static void (*sithCogThing_GetParticleGrowthSpeed)(sithCog* ctx) = (void*)0x00504D60;
static void (*sithCogThing_SetParticleGrowthSpeed)(sithCog* ctx) = (void*)0x00504DA0;
static void (*sithCogThing_GetParticleTimeoutRate)(sithCog* ctx) = (void*)0x00504DE0;
static void (*sithCogThing_SetParticleTimeoutRate)(sithCog* ctx) = (void*)0x00504E20;
static void (*sithCogThing_GetXFlags)(sithCog* ctx) = (void*)0x00504E60;
static void (*sithCogThing_SetXFlags)(sithCog* ctx) = (void*)0x00504EF0;
static void (*sithCogThing_ClearXFlags)(sithCog* ctx) = (void*)0x00504F80;
static void (*sithCogThing_TakeItem)(sithCog* ctx) = (void*)0x00505020;
static void (*sithCogThing_HasLos)(sithCog* ctx) = (void*)0x00505060;
static void (*sithCogThing_GetThingFireOffset)(sithCog* ctx) = (void*)0x005050C0;
static void (*sithCogThing_SetThingFireOffset)(sithCog* ctx) = (void*)0x00505100;
static void (*sithCogThing_GetThingUserdata)(sithCog* ctx) = (void*)0x00505150;
static void (*sithCogThing_SetThingUserdata)(sithCog* ctx) = (void*)0x00505190;
static void (*sithCogThing_GetThingCollideSize)(sithCog* ctx) = (void*)0x005051C0;
static void (*sithCogThing_SetThingCollideSize)(sithCog* ctx) = (void*)0x00505200;
static void (*sithCogThing_GetThingMoveSize)(sithCog* ctx) = (void*)0x00505230;
static void (*sithCogThing_SetThingMoveSize)(sithCog* ctx) = (void*)0x00505270;
static void (*sithCogThing_GetThingMass)(sithCog* ctx) = (void*)0x005052A0;
static void (*sithCogThing_SetThingMass)(sithCog* ctx) = (void*)0x005052E0;
static void (*sithCogThing_SyncThingPos)(sithCog* ctx) = (void*)0x00505340;
static void (*sithCogThing_SyncThingAttachment)(sithCog* ctx) = (void*)0x00505360;
static void (*sithCogThing_SyncThingState)(sithCog* ctx) = (void*)0x00505390;
static void (*sithCogThing_GetMajorMode)(sithCog* ctx) = (void*)0x005053B0;

void sithCogThing_Initialize(void* ctx)
{
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_WaitForStop, "waitforstop");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_StopThing, "stopthing");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_DestroyThing, "destroything");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingHealth, "getthinghealth");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingHealth, "gethealth");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_HealThing, "healthing");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingLight, "getthinglight");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingLight, "setthinglight");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingLight, "thinglight");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ThingLightAnim, "thinglightanim");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_Rotate, "rotate");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_CreateThing, "creatething");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_CreateThingNr, "createthingnr");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_CreateThingAtPos, "createthingatpos");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_CreateThingAtPosNr, "createthingatposnr");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_RotatePivot, "rotatepivot");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_CaptureThing, "capturething");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ReleaseThing, "releasething");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingVel, "setthingvel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_AddThingVel, "addthingvel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ApplyForce, "applyforce");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_DetachThing, "detachthing");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetAttachFlags, "getattachflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetAttachFlags, "getthingattachflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_AttachThingToSurf, "attachthingtosurf");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_AttachThingToThing, "attachthingtothing");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetArmedMode, "setarmedmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingFlags, "setthingflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearThingFlags, "clearthingflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_TeleportThing, "teleportthing");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingType, "setthingtype");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetCollideType, "setcollidetype");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetHeadlightIntensity, "setheadlightintensity");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingGeoMode, "getthinggeomode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingGeoMode, "setthinggeomode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingLightMode, "getthinglightmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingLightMode, "setthinglightmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingTexMode, "getthingtexmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingTexMode, "setthingtexmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingCurGeoMode, "getthingcurgeomode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingCurGeoMode, "setthingcurgeomode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingCurLightMode, "getthingcurlightmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingCurLightmode, "setthingcurlightmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingCurTexMode, "getthingcurtexmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingCurTexMode, "setthingcurtexmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetActorExtraSpeed, "setactorextraspeed");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingType, "getthingtype");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_IsMoving, "isthingmoving");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_IsMoving, "ismoving");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetCurFrame, "getcurframe");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetGoalFrame, "getgoalframe");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingParent, "getthingparent");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingSector, "getthingsector");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingPos, "getthingpos");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingPos, "setthingpos");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingVel, "getthingvel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingUvec, "getthinguvec");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingLvec, "getthinglvec");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingRvec, "getthingrvec");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingFlags, "getthingflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetCollideType, "getcollidetype");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetHeadlightIntensity, "getheadlightintensity");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_IsThingVisible, "isthingvisible");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingPulse, "setthingpulse");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingTimer, "setthingtimer");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetInv, "getinv");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetInv, "setinv");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ChangeInv, "changeinv");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetInvCog, "getinvcog");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetInvMin, "getinvmin");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetInvMax, "getinvmax");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetCurInvWeapon, "getcurinvweapon");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetCurInvWeapon, "setcurinvweapon");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_PlayKey, "playkey");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_StopKey, "stopkey");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingModel, "setthingmodel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingModel, "getthingmodel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_PlayMode, "playmode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetMajorMode, "getmajormode");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_FirstThingInSector, "firstthinginsector");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_NextThingInSector, "nextthinginsector");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_PrevThingInSector, "prevthinginsector");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_MoveToFrame, "movetoframe");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SkipToFrame, "skiptoframe");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_JumpToFrame, "jumptoframe");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_PathMovePause, "pathmovepause");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_PathMoveResume, "pathmoveresume");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingTemplate, "getthingtemplate");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_DamageThing, "damagething");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetLifeLeft, "setlifeleft");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetLifeLeft, "getlifeleft");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingThrust, "setthingthrust");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingThrust, "getthingthrust");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetHealth, "setthinghealth");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetHealth, "sethealth");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_AmputateJoint, "amputatejoint");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetActorWeapon, "setactorweapon");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetActorWeapon, "getactorweapon");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetPhysicsFlags, "getphysicsflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetPhysicsFlags, "setphysicsflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearPhysicsFlags, "clearphysicsflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SkillTarget, "skilltarget");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ParseArg, "parsearg");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingRotVel, "getthingrotvel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingRotVel, "setthingrotvel");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingLook, "setthinglook");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_IsCrouching, "isthingcrouching");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_IsCrouching, "iscrouching");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingClassCog, "getthingclasscog");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingClassCog, "setthingclasscog");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingCaptureCog, "getthingcapturecog");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingCaptureCog, "setthingcapturecog");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingRespawn, "getthingrespawn");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingSignature, "getthingsignature");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingAttachFlags, "setthingattachflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearThingAttachFlags, "clearthingattachflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetParticleSize, "getparticlesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetParticleSize, "setparticlesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetParticleGrowthSpeed, "getparticlegrowthspeed");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetParticleGrowthSpeed, "setparticlegrowthspeed");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetParticleTimeoutRate, "getparticletimeoutrate");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetParticleTimeoutRate, "setparticletimeoutrate");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "gettypeflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "settypeflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "cleartypeflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "getactorflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "setactorflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "clearactorflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "getweaponflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "setweaponflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "clearweaponflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "getexplosionflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "setexplosionflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "clearexplosionflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "getitemflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "setitemflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "clearitemflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetXFlags, "getparticleflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetXFlags, "setparticleflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_ClearXFlags, "clearparticleflags");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_TakeItem, "takeitem");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_HasLos, "haslos");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingFireOffset, "getthingfireoffset");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingFireOffset, "setthingfireoffset");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingUserdata, "getthinguserdata");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingUserdata, "setthinguserdata");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingCollideSize, "getthingcollidesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingCollideSize, "setthingcollidesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingMoveSize, "getthingmovesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingMoveSize, "setthingmovesize");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_GetThingMass, "getthingmass");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SetThingMass, "setthingmass");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SyncThingPos, "syncthingpos");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SyncThingAttachment, "syncthingattachment");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_SyncThingState, "syncthingstate");
    sithCogScript_RegisterVerb(ctx, (intptr_t)sithCogThing_AttachThingToThingEx, "attachthingtothingex");
}
