// dwWidget — the DroidWorks GUI base class + the shared window-message input
// router + the widget.rec input recorder.
//
// Decompiled from DroidWorks.exe, unit range 0x442390-0x4429dx, plus the base
// virtual default bodies mis-binned in other units (@0x4018xx, @0x407ee0,
// @0x404220, @0x402cc0) and the shared COMDATs dwWidget_OnHoverNotify@0x419780
// and dwWidget_DispatchMsg@0x444d00 (mislabeled stdBitmapRle_FUN_00444d00 in
// Ghidra). See dwWidget.h for the vtable slot map and layout notes.
//
// Adaptations (each marked with a Note below):
//  - SetCapture/ReleaseCapture Win32 calls dropped (SDL owns mouse capture);
//    the dwWidget_bCaptured bookkeeping is kept.
//  - the WM_PAINT present maps to stdDisplay_DDrawGdiSurfaceFlip() (the
//    binary's DW-stdDisplay flip @0x4fdc60), same mapping as dwDisplay.cpp.
//  - OnHoverNotify takes the msg sender explicitly (the binary read the
//    derived class's field at raw offset +0x10 — see dwWidget.h).

#include "Dw/dwWidget.h"

#include "Dw/dwImage.h"   // dwImageBits/dwImageDesc (plain-C structs)
#include "Dw/dwDisplay.h" // dwDisplay_AddDirtyRect
#include "Dw/dwCursor.h"  // dwCursor_pos, dwCursor_Redraw

#include "jk.h"
#include "stdPlatform.h"

// These engine headers have no extern "C" guards of their own — wrap at include site.
extern "C" {
#include "Win95/Window.h"     // Window_AddMsgHandler/Window_RemoveMsgHandler
#include "Win95/stdDisplay.h" // stdDisplay_pCurVideoMode, stdDisplay_DDrawGdiSurfaceFlip
}

extern "C" HostServices* dwMain_pHS; // the DW host-services pointer (dwMain.c); binary global dwHS @0x6b6258

// ---- module globals/statics --------------------------------------------------

dwWidget* dwWidget_pDefault = NULL;     // binary: 0x541c00
dwWidget* dwWidget_pMouseTarget = NULL; // binary: 0x541bfc
int dwWidget_count = 0;                 // binary: 0x541c04
int dwWidget_bInputDisabled = 0;        // binary: 0x541c18
uint8_t dwWidget_bCaptured = 0;         // binary: 0x541c08

static stdFile_t dwWidget_recordFile = 0;     // binary: 0x541c0c — open widget.rec handle
static int dwWidget_bRecordPending = 0;          // binary: 0x541c14 — armed, start tick not latched yet
static uint32_t dwWidget_recordStartTick = 0;    // binary: 0x541c10

// Note: no binary counterpart — soft-reset support (see dwWidget.h).
void dwWidget_Startup()
{
    if (dwWidget_recordFile && dwMain_pHS)
        dwWidget_RecordStop();
    if (dwWidget_count != 0)
        Window_RemoveMsgHandler(dwWidget_MsgHandler); // stale handler from a leaked widget

    dwWidget_pDefault = NULL;
    dwWidget_pMouseTarget = NULL;
    dwWidget_count = 0;
    dwWidget_bInputDisabled = 0;
    dwWidget_bCaptured = 0;
    dwWidget_recordFile = 0;
    dwWidget_bRecordPending = 0;
    dwWidget_recordStartTick = 0;
}

// ---- ctors/dtor ---------------------------------------------------------------

// @442390 (Ghidra: dwWidget_CtorDefault) — full-screen widget.
dwWidget::dwWidget()
{
    this->bEnabled = 1;
    this->left = 0;
    this->top = 0;
    // Note: guard added; stdDisplay_pCurVideoMode (binary global 0x6478f8) is
    // always non-NULL by the time the binary constructs widgets.
    if (stdDisplay_pCurVideoMode)
    {
        this->right = (int16_t)stdDisplay_pCurVideoMode->format.width;
        this->bottom = (int16_t)stdDisplay_pCurVideoMode->format.height;
    }
    else
    {
        this->right = 0;
        this->bottom = 0;
    }

    dwWidget_count++;
    if (dwWidget_count == 1)
        Window_AddMsgHandler(dwWidget_MsgHandler);
}

// @442400 (Ghidra: dwWidget_Ctor)
dwWidget::dwWidget(dwRect* pRect)
{
    this->bEnabled = 1;
    this->left = pRect->left;
    this->top = pRect->top;
    this->right = pRect->right;
    this->bottom = pRect->bottom;

    dwWidget_count++;
    if (dwWidget_count == 1)
        Window_AddMsgHandler(dwWidget_MsgHandler);
}

// @442440 (Ghidra: dwWidget_Dtor; identical COMDAT copy j_dwWidgetDtor@409fb0;
// the vtbl-slot-0 scalar-deleting wrapper @4423e0 is generated by the compiler)
dwWidget::~dwWidget()
{
    if (dwWidget_pDefault == this)
    {
        stdPlatform_Printf("Warning: destroying default widget!\n");
        dwWidget_pDefault = NULL;
    }
    if (dwWidget_pMouseTarget == this)
        dwWidget_pMouseTarget = NULL;

    dwWidget_count--;
    if (dwWidget_count == 0)
        Window_RemoveMsgHandler(dwWidget_MsgHandler);
}

// ---- base virtual defaults ------------------------------------------------------

// vtbl +0x04/+0x08/+0x0c/+0x10/+0x18 all share one stub in the binary
// (@401850, Ghidra: dwWidget_DefaultInput — xor al,al; ret 8).
int dwWidget::OnMouseMove(int16_t x, int16_t y) { (void)x; (void)y; return 0; } // @401850
int dwWidget::OnMouseDown(int16_t x, int16_t y) { (void)x; (void)y; return 0; } // @401850
int dwWidget::OnMouseUp(int16_t x, int16_t y) { (void)x; (void)y; return 0; }   // @401850
int dwWidget::OnKey(int key, int repeat) { (void)key; (void)repeat; return 0; } // @401850

// @407ee0 (dwGui_NullVirtual) — per-frame tick default: no-op.
void dwWidget::Update(float dt) { (void)dt; }

int dwWidget::OnHover(int16_t x, int16_t y) { (void)x; (void)y; return 0; } // @401850

// @404220 (dwGui_OnMessageDefault — shared "return 0" stub in ~28 vtables)
int dwWidget::OnMessage(dwWidgetMsg* pMsg) { (void)pMsg; return 0; }

// @401860
void dwWidget::Enable()
{
    this->bEnabled = 1;
}

// @401870
void dwWidget::Disable()
{
    this->bEnabled = 0;
}

// @401880
void dwWidget::Move(int16_t dx, int16_t dy)
{
    this->left += dx;
    this->top += dy;
    this->right += dx;
    this->bottom += dy;
}

// @4018a0 — left/top inclusive, right/bottom exclusive.
int dwWidget::ContainsPoint(dwPoint* pPt)
{
    if (this->left <= pPt->x && pPt->x < this->right
        && this->top <= pPt->y && pPt->y < this->bottom)
    {
        return 1;
    }
    return 0;
}

// @4018d0 — despite the name, this CLIPS the caller's rect to the widget
// rect (dwRect_Clip zeroes *pRect when the intersection is empty). Pass a
// full-surface rect to "get" the widget rect.
void dwWidget::GetRect(dwRect* pRect)
{
    dwRect_Clip(pRect, this->GetRectPtr());
}

// @4424a0
void dwWidget::Invalidate()
{
    dwDisplay_AddDirtyRect(this->GetRectPtr());
}

// @4018e0 — this widget when the point is inside it, else NULL (calls
// ContainsPoint through the vtable).
dwWidget* dwWidget::HitTest(dwPoint* pPt)
{
    if (this->ContainsPoint(pPt))
        return this;
    return NULL;
}

// @402cc0 (shared no-op default for both +0x3c and +0x40)
void dwWidget::EnsureImages() {}
void dwWidget::FreeImages() {}

// @442540 — paint default: no-op.
void dwWidget::Draw(dwImageBits* pDestBits, dwRect* pClipRect)
{
    (void)pDestBits;
    (void)pClipRect;
}

// ---- non-virtual methods ----------------------------------------------------------

// @4424b0 — draw THIS widget as a container child: clip = dest bounds
// ∩ pClipRect ∩ widget rect; Draw only when non-empty.
void dwWidget::DrawChild(dwImageBits* pDestBits, dwRect* pClipRect)
{
    dwRect rect;

    rect.left = 0;
    rect.top = 0;
    rect.right = (int16_t)pDestBits->pDesc->width;
    rect.bottom = (int16_t)pDestBits->pDesc->height;
    if (pClipRect)
        dwRect_Clip(&rect, pClipRect);
    this->GetRect(&rect); // virtual +0x30: rect ∩= widget rect (zeroed when empty)
    if ((int16_t)(rect.right - rect.left) != 0 && (int16_t)(rect.bottom - rect.top) != 0)
        this->Draw(pDestBits, &rect); // virtual +0x44
}

// @419780 — shared COMDAT OnHover body; see the signature Note in dwWidget.h
// (the binary read pSender from the derived class's field at raw offset +0x10).
int dwWidget::OnHoverNotify(void* pSender)
{
    dwWidgetMsg msg;

    msg.code = 0x7531; // 30001: hover notification
    msg.pSender = pSender;
    msg.param = 0;
    msg.pTarget = NULL;
    dwWidget_DispatchMsg(&msg, NULL);
    return 1;
}

// ---- message dispatch ----------------------------------------------------------------

// @444d00 (Ghidra: stdBitmapRle_FUN_00444d00 — mislabeled; __thiscall on the
// msg in the binary). extern "C": called from dwSound.cpp's finish-message
// reaper and future C units.
extern "C" uint32_t dwWidget_DispatchMsg(void* pMsg, void* pOverrideWidget)
{
    dwWidgetMsg* pM = (dwWidgetMsg*)pMsg;
    dwWidget* pTarget;

    pTarget = dwWidget_pDefault;
    if (pM->pTarget)
        pTarget = pM->pTarget;
    if (pOverrideWidget)
        pTarget = (dwWidget*)pOverrideWidget;

    if (pTarget && pTarget->bEnabled && pM->code != 0 && pM->code != -1)
        return (uint32_t)pTarget->OnMessage(pM); // vtbl +0x1c
    // Note: the binary only zeroed AL here (xor al,al), leaving EAX's upper
    // bits undefined; callers only test the low byte. Plain 0 here.
    return 0;
}

// ---- input gating ----------------------------------------------------------------------

// @4425c0
void dwWidget_DisableInput()
{
    dwWidget_bInputDisabled = 1;
}

// @4425d0
void dwWidget_EnableInput()
{
    dwWidget_bInputDisabled = 0;
}

// ---- widget.rec input recorder ---------------------------------------------------------

// @442550
void dwWidget_RecordStart(char* pFilename)
{
    if (dwWidget_recordFile == 0)
    {
        dwWidget_recordFile = dwMain_pHS->fileOpen(pFilename, "w");
        if (dwWidget_recordFile != 0)
        {
            dwWidget_bRecordPending = 1;
            stdPlatform_Printf("Ready to record to %s\n", pFilename);
        }
    }
}

// @442590
void dwWidget_RecordStop()
{
    if (dwWidget_recordFile != 0)
    {
        dwMain_pHS->fileClose(dwWidget_recordFile);
        dwWidget_recordFile = 0;
        stdPlatform_Printf("Widget recording terminated...\n");
    }
}

// @442960 — one cue line per event; the timestamp is seconds since the FIRST
// recorded event (some_float = timer ticks per second, 1000).
void dwWidget_RecordEvent(char evt, uint32_t a, uint32_t b)
{
    uint32_t tick;

    tick = dwMain_pHS->getTimerTick();
    if (dwWidget_bRecordPending != 0)
    {
        dwWidget_bRecordPending = 0;
        dwWidget_recordStartTick = tick;
        stdPlatform_Printf("Widget recording started...\n");
    }
    dwMain_pHS->filePrintf(dwWidget_recordFile, "%09.4f\t%c\t%lu\t%lu\n",
                           (double)((float)(tick - dwWidget_recordStartTick) / (float)dwMain_pHS->some_float),
                           (int)evt, (unsigned long)a, (unsigned long)b);
}

// ---- the shared window message pump ------------------------------------------------------

// Note: no binary counterpart. The Win32 WM_CHAR/WM_KEYDOWN lParam repeat-count
// (low word) is >=1 for any real keypress on Windows, but OpenJKDF2's SDL event
// bridge delivers it as 0 on a fresh press. Clamp to >=1 so the DW key
// consumers that gate on it (dwGuiTextEntry::OnKey) register real presses.
static int dwWidget_WinKeyRepeat(LPARAM lParam)
{
    int repeat = (int)((uint32_t)lParam & 0xffff);
    return repeat != 0 ? repeat : 1;
}

// @4425e0 — installed via Window_AddMsgHandler by the first widget ctor.
// Always returns 0 and always writes *pResult = 0 (the binary never consumed
// the message).
int dwWidget_MsgHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam, LRESULT* pResult)
{
    dwWidget* pKeyTarget;
    dwWidget* pMouseTarget;

    *pResult = 0;
    pKeyTarget = dwWidget_pDefault;
    pMouseTarget = dwWidget_pMouseTarget;
    if (pMouseTarget == NULL)
        pMouseTarget = dwWidget_pDefault;

    switch (msg)
    {
    case WM_KEYDOWN: // 0x100 — map the extended keys to DW key codes
        if (pKeyTarget != NULL && pKeyTarget->bEnabled != 0)
        {
            char code = 0;
            switch (wParam)
            {
            case 0x13: code = 0x01; break; // VK_PAUSE
            case 0x25: code = 0x1c; break; // VK_LEFT
            case 0x26: code = 0x1e; break; // VK_UP
            case 0x27: code = 0x1d; break; // VK_RIGHT
            case 0x28: code = 0x1f; break; // VK_DOWN
            case 0x70: code = 0x0f; break; // VK_F1
            case 0x71: code = 0x10; break; // VK_F2
            case 0x72: code = 0x11; break; // VK_F3
            case 0x73: code = 0x12; break; // VK_F4
            case 0x74: code = 0x13; break; // VK_F5
            case 0x75: code = 0x14; break; // VK_F6
            case 0x76: code = 0x15; break; // VK_F7
            case 0x77: code = 0x16; break; // VK_F8
            case 0x78: code = 0x17; break; // VK_F9
            case 0x79: code = 0x18; break; // VK_F10
            case 0x7a: code = 0x19; break; // VK_F11
            case 0x7b: code = 0x1a; break; // VK_F12
            }
            if (code != 0)
            {
                if (dwWidget_recordFile != 0)
                    dwWidget_RecordEvent('K', (uint32_t)code, (uint32_t)lParam & 0xffff);
                // Note: the binary received the Win32 WM_CHAR/WM_KEYDOWN lParam
                // repeat-count, which is always >=1 for a real keypress; SDL's
                // event bridge (Window.c) supplies it as 0 on a fresh press
                // (SDL_EVENT_TEXT_INPUT hardcodes 0; key events pass SDL's
                // inverted repeat flag). dwGuiTextEntry::OnKey DROPS keys with
                // repeat==0, so force a Windows-style count of >=1 here.
                pKeyTarget->OnKey(code, dwWidget_WinKeyRepeat(lParam)); // vtbl +0x10
            }
        }
        break;

    case WM_CHAR: // 0x102
        if (pKeyTarget != NULL && pKeyTarget->bEnabled != 0)
        {
            if (dwWidget_recordFile != 0)
                dwWidget_RecordEvent('K', (uint32_t)wParam, (uint32_t)lParam & 0xffff);
            // Note: see the WM_KEYDOWN case — force a Win32-style repeat count
            // of >=1 so dwGuiTextEntry accepts the char (SDL supplies 0).
            pKeyTarget->OnKey((int)wParam, dwWidget_WinKeyRepeat(lParam)); // vtbl +0x10
        }
        break;

    case WM_PAINT: // 0x0f
        // Note: the binary called the DW-stdDisplay GDI/DDraw present
        // @0x4fdc60; stdDisplay_DDrawGdiSurfaceFlip is the OpenJKDF2
        // equivalent (same mapping as dwDisplay_Present).
        stdDisplay_DDrawGdiSurfaceFlip();
        break;

    case WM_MOUSEMOVE: // 0x200
        if (dwWidget_bInputDisabled == 0)
        {
            dwCursor_pos.x = (int16_t)((uint32_t)lParam & 0xffff);
            dwCursor_pos.y = (int16_t)((uint32_t)lParam >> 16);
            if (pMouseTarget != NULL && pMouseTarget->bEnabled != 0)
                pMouseTarget->OnMouseMove((int16_t)((uint32_t)lParam & 0xffff), (int16_t)((uint32_t)lParam >> 16)); // vtbl +0x04
        }
        dwCursor_Redraw();
        break;

    case WM_LBUTTONDOWN: // 0x201 — recorded even while input is disabled (binary quirk)
        if (dwWidget_recordFile != 0)
            dwWidget_RecordEvent('D', (uint32_t)lParam & 0xffff, (uint32_t)lParam >> 16);
        // Note: SetCapture(hWnd) dropped — SDL owns mouse capture; the
        // bCaptured bookkeeping is kept.
        dwWidget_bCaptured = 1;
        if (dwWidget_bInputDisabled == 0 && pMouseTarget != NULL && pMouseTarget->bEnabled != 0)
            pMouseTarget->OnMouseDown((int16_t)((uint32_t)lParam & 0xffff), (int16_t)((uint32_t)lParam >> 16)); // vtbl +0x08
        break;

    case WM_LBUTTONUP: // 0x202 — recorded even while input is disabled (binary quirk)
        if (dwWidget_recordFile != 0)
            dwWidget_RecordEvent('U', (uint32_t)lParam & 0xffff, (uint32_t)lParam >> 16);
        // Note: ReleaseCapture() dropped (see above).
        dwWidget_bCaptured = 0;
        if (dwWidget_bInputDisabled == 0 && pMouseTarget != NULL && pMouseTarget->bEnabled != 0)
            pMouseTarget->OnMouseUp((int16_t)((uint32_t)lParam & 0xffff), (int16_t)((uint32_t)lParam >> 16)); // vtbl +0x0c
        break;

    case WM_RBUTTONDOWN: // 0x204 — Ctrl+Shift+RightClick toggles the recorder
        if (dwWidget_bInputDisabled == 0 && ((uint32_t)wParam & 0xc) == 0xc) // MK_CONTROL|MK_SHIFT
        {
            if (dwWidget_recordFile == 0)
                dwWidget_RecordStart((char*)"widget.rec");
            else
                dwWidget_RecordStop();
        }
        break;

    default:
        break;
    }
    return 0;
}
