#define FLEX_COMPRESSED
/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: flex.skel,v 2.0 89/06/20 15:49:46 vern Locked $
 */

#include <stdio.h>

#define FLEX_SCANNER

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of input buffer */
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

#define ECHO fputs( yytext, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0
#define yyterminate() return ( YY_NULL )

/* report a fatal error */
#define YY_FATAL_ERROR(msg) \
	{ \
	fputs( msg, stderr ); \
	putc( '\n', stderr ); \
	exit( 1 ); \
	}

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE goto new_file

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#ifdef __STDC__
#define YY_DECL int yylex( void )
#else
#define YY_DECL int yylex()
#endif

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

/* returns the length of the matched text */
#define yyleng (yy_cp - yy_bp)

#define EOB_ACT_RESTART_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	{ \
	*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
	yy_c_buf_p = yy_cp = yy_bp + n; \
	YY_DO_BEFORE_ACTION; /* set up yytext again */ \
	}

#define unput(c) yyunput( c, yy_bp )

#define YY_USER_ACTION

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
char *yytext;

#ifndef __STDC__
#define const
#endif

# line 1 "/home/maxamillion/byacc-14/cog_lex.txt"
#define INITIAL 0
# line 7 "/home/maxamillion/byacc-14/cog_lex.txt"
#include <stdio.h>
#include "y.tab.h"

int linenum = 0;

void newline();
# line 15 "/home/maxamillion/byacc-14/cog_lex.txt"
#define YY_END_OF_BUFFER 57
typedef int yy_state_type;
static const short int yy_accept[121] =
    {   0,
        0,    0,   57,   55,   54,   53,   53,   40,   55,   46,
       48,   39,   55,   34,   35,   44,   43,   31,   42,   38,
       47,   16,   16,   32,   28,   49,   33,   50,   36,   37,
       51,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   29,   52,   30,   41,   27,    0,   20,    0,
       46,   22,    0,   21,    0,   18,   45,   19,   15,    0,
        0,   16,   24,   26,   25,   13,   13,   13,   13,    3,
       13,   13,   13,   13,    7,   13,   13,   13,   23,    0,
       45,   18,    0,    0,   17,   14,   13,   13,   13,   13,
       11,    5,   13,   13,   13,   13,    0,   18,    0,    0,

       19,   13,   12,   13,    4,    6,   13,    8,   13,    0,
       18,    1,   13,   13,   10,   13,    9,   13,    2,    0
    } ;

static const char yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   30,   40,   41,   30,   42,   43,   44,
       30,   45,   46,   47,   48,   30,   49,   50,   30,   30,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   30,   40,   41,   30,   42,
       43,   44,   30,   45,   46,   47,   48,   30,   49,   50,
       30,   30,   51,   52,   53,   54,    1
    } ;

static const char yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static const short int yy_base[126] =
    {   0,
        0,    0,  197,  198,  198,  198,  198,  172,   49,    0,
      198,  186,   46,  198,  198,  198,  198,  198,  198,   38,
      176,   42,   46,  198,  198,  169,  168,  167,  198,  198,
      198,    0,  145,   29,  146,   26,  145,  144,  150,  150,
      137,  145,  198,  130,  198,  198,  198,   58,  198,  178,
        0,  198,   59,  198,  177,   55,    0,   59,   63,   77,
       68,   88,  198,  198,  198,    0,  144,  137,  135,    0,
      130,  141,  129,  126,    0,  125,  128,  131,  198,   95,
        0,   93,  102,   51,  100,  105,  138,  127,  120,  131,
        0,    0,  122,  116,  119,  120,  107,  110,  128,  112,

      114,  115,    0,  104,    0,    0,   90,    0,   82,  126,
      130,    0,   68,   64,    0,   47,    0,   54,    0,  198,
      150,  153,  156,   81,  159
    } ;

static const short int yy_def[126] =
    {   0,
      120,    1,  120,  120,  120,  120,  120,  120,  121,  122,
      120,  120,  123,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  120,  120,  120,  120,  120,  121,  120,  121,
      122,  120,  123,  120,  123,  120,  125,  120,  120,  120,
      120,  120,  120,  120,  120,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  120,  120,
      125,  120,  120,  120,  120,  120,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  120,  120,  120,  120,

      120,  124,  124,  124,  124,  124,  124,  124,  124,  120,
      120,  124,  124,  124,  124,  124,  124,  124,  124,    0,
      120,  120,  120,  120,  120
    } ;

static const short int yy_nxt[253] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,    4,   30,   31,   32,
       32,   33,   34,   35,   36,   37,   38,   32,   39,   32,
       32,   32,   32,   32,   40,   41,   32,   32,   42,   32,
       43,   44,   45,   46,   49,   54,   56,   56,   58,   68,
       59,   59,   58,   49,   62,   62,   71,   72,   54,   85,
       85,   69,   55,   56,   56,   50,   60,   82,   82,   58,
       60,   59,   59,   66,   50,   55,   86,   86,  119,   80,
       84,   61,   84,   83,  118,   85,   85,   60,   86,   86,

       86,   86,   86,   86,   58,  117,   62,   62,   97,  116,
       97,   82,   82,   98,   98,  100,  115,  100,   85,   85,
      101,  101,   60,   86,   86,   98,   98,   99,   98,   98,
      101,  101,  101,  101,  114,   86,   86,   86,   86,   86,
       86,  110,  113,  110,  111,  111,  111,  111,  111,  111,
       48,   48,   48,   51,  112,   51,   53,   53,   53,   81,
      109,   81,  108,  107,  106,  105,  104,  103,  102,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,  120,
      120,   79,   78,   77,   76,   75,   74,   73,   70,   67,
       65,   64,   63,   57,   52,   47,  120,    3,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

static const short int yy_chk[253] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   13,   20,   20,   22,   34,
       22,   22,   23,   48,   23,   23,   36,   36,   53,   84,
       84,   34,   13,   56,   56,    9,   22,   58,   58,   59,
       23,   59,   59,  124,   48,   53,   61,   61,  118,   56,
       60,   22,   60,   58,  116,   60,   60,   59,   61,   61,

       61,   61,   61,   61,   62,  114,   62,   62,   80,  113,
       80,   82,   82,   80,   80,   83,  109,   83,   85,   85,
       83,   83,   62,   86,   86,   97,   97,   82,   98,   98,
      100,  100,  101,  101,  107,   86,   86,   86,   86,   86,
       86,   99,  104,   99,  110,  110,   99,   99,  111,  111,
      121,  121,  121,  122,  102,  122,  123,  123,  123,  125,
       96,  125,   95,   94,   93,   90,   89,   88,   87,   78,
       77,   76,   74,   73,   72,   71,   69,   68,   67,   55,
       50,   44,   42,   41,   40,   39,   38,   37,   35,   33,
       28,   27,   26,   21,   12,    8,    3,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
static char *yy_c_buf_p;	/* points to current character in buffer */
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* true when we've seen an EOF for the current input file */
static int yy_eof_has_been_seen;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

/* yy_ch_buf has to be 2 characters longer than YY_BUF_SIZE because we need
 * to put in 2 end-of-buffer characters (this is explained where it is
 * done) at the end of yy_ch_buf
 */
static char yy_ch_buf[YY_BUF_SIZE + 2];

/* yy_hold_char holds the character lost when yytext is formed */
static char yy_hold_char;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

#ifdef __STDC__
static yy_state_type yy_get_previous_state( void );
static int yy_get_next_buffer( void );
static void yyunput( int c, char *buf_ptr );
static int input( void );
static void yyrestart( FILE *input_file );
#else
static yy_state_type yy_get_previous_state();
static int yy_get_next_buffer();
static void yyunput();
static int input();
static void yyrestart();
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

new_file:
	/* this is where we enter upon encountering an end-of-file and
	 * yywrap() indicating that we should continue processing
	 */

	/* we put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	yy_ch_buf[0] = '\n';
	yy_n_chars = 1;

	/* we always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yy_eof_has_been_seen = 0;

	yytext = yy_c_buf_p = &yy_ch_buf[1];
	yy_hold_char = *yy_c_buf_p;
	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	do
	    {
	    register char yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 121 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 120 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

	/* bogus while loop to let YY_BACK_TRACK, EOB_ACT_LAST_MATCH,
	 * and EOF actions branch here without introducing an optimizer-
	 * daunting goto
	 */
	while ( 1 )
	    {
	    yy_act = yy_accept[yy_current_state];

	    YY_DO_BEFORE_ACTION;
	    YY_USER_ACTION;

#ifdef FLEX_DEBUG
	    fprintf( stderr, "--accepting rule #%d (\"%s\")\n",
		     yy_act, yytext );
#endif

do_action:	/* this label is used only to access EOF actions */
	    switch ( yy_act )
		{
		case 0: /* must backtrack */
		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;
		continue; /* go to "YY_DO_BEFORE_ACTION" */

case 1:
# line 17 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(BREAK); }
	YY_BREAK
case 2:
# line 18 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONTINUE); }
	YY_BREAK
case 3:
# line 19 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(DO); }
	YY_BREAK
case 4:
# line 20 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(ELSE); }
	YY_BREAK
case 5:
# line 21 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(FOR); }
	YY_BREAK
case 6:
# line 22 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(GOTO); }
	YY_BREAK
case 7:
# line 23 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(IF); }
	YY_BREAK
case 8:
# line 24 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(RETURN); }
	YY_BREAK
case 9:
# line 25 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(RETURN); }
	YY_BREAK
case 10:
# line 26 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(WHILE); }
	YY_BREAK
case 11:
# line 27 "/home/maxamillion/byacc-14/cog_lex.txt"
{ yyterminate(); }
	YY_BREAK
case 12:
# line 28 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CALL); }
	YY_BREAK
case 13:
# line 30 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(check_type()); }
	YY_BREAK
case 14:
# line 32 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 15:
# line 33 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 16:
# line 34 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 17:
# line 37 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 18:
# line 38 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 19:
# line 39 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(CONSTANT); }
	YY_BREAK
case 20:
# line 41 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(STRING_LITERAL); }
	YY_BREAK
case 21:
# line 42 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(VECTOR_CONSTANT); }
	YY_BREAK
case 22:
# line 44 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(AND_OP); }
	YY_BREAK
case 23:
# line 45 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(OR_OP); }
	YY_BREAK
case 24:
# line 46 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(LE_OP); }
	YY_BREAK
case 25:
# line 47 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(GE_OP); }
	YY_BREAK
case 26:
# line 48 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(EQ_OP); }
	YY_BREAK
case 27:
# line 49 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(NE_OP); }
	YY_BREAK
case 28:
# line 50 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(';'); }
	YY_BREAK
case 29:
# line 51 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('{'); }
	YY_BREAK
case 30:
# line 52 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('}'); }
	YY_BREAK
case 31:
# line 53 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(','); }
	YY_BREAK
case 32:
# line 54 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(':'); }
	YY_BREAK
case 33:
# line 55 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('='); }
	YY_BREAK
case 34:
# line 56 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('('); }
	YY_BREAK
case 35:
# line 57 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(')'); }
	YY_BREAK
case 36:
# line 58 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('['); }
	YY_BREAK
case 37:
# line 59 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return(']'); }
	YY_BREAK
case 38:
# line 60 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('.'); }
	YY_BREAK
case 39:
# line 61 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('&'); }
	YY_BREAK
case 40:
# line 62 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('!'); }
	YY_BREAK
case 41:
# line 63 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('~'); }
	YY_BREAK
case 42:
# line 64 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('-'); }
	YY_BREAK
case 43:
# line 65 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('+'); }
	YY_BREAK
case 44:
# line 66 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('*'); }
	YY_BREAK
case 45:
# line 67 "/home/maxamillion/byacc-14/cog_lex.txt"
{ comment(); }
	YY_BREAK
case 46:
# line 68 "/home/maxamillion/byacc-14/cog_lex.txt"
{ comment(); }
	YY_BREAK
case 47:
# line 69 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('/'); }
	YY_BREAK
case 48:
# line 70 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('%'); }
	YY_BREAK
case 49:
# line 71 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('<'); }
	YY_BREAK
case 50:
# line 72 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('>'); }
	YY_BREAK
case 51:
# line 73 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('^'); }
	YY_BREAK
case 52:
# line 74 "/home/maxamillion/byacc-14/cog_lex.txt"
{ return('|'); }
	YY_BREAK
case 53:
# line 76 "/home/maxamillion/byacc-14/cog_lex.txt"
{ linenum++; }
	YY_BREAK
case 54:
# line 77 "/home/maxamillion/byacc-14/cog_lex.txt"
{ }
	YY_BREAK
case 55:
# line 78 "/home/maxamillion/byacc-14/cog_lex.txt"
{ /* ignore bad characters */ }
	YY_BREAK
case 56:
# line 80 "/home/maxamillion/byacc-14/cog_lex.txt"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

		case YY_END_OF_BUFFER:
		    /* undo the effects of YY_DO_BEFORE_ACTION */
		    *yy_cp = yy_hold_char;

		    yytext = yy_bp;

		    switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
			    {
			    if ( yywrap() )
				{
				/* note: because we've taken care in
				 * yy_get_next_buffer() to have set up yytext,
				 * we can now set up yy_c_buf_p so that if some
				 * total hoser (like flex itself) wants
				 * to call the scanner after we return the
				 * YY_NULL, it'll still work - another YY_NULL
				 * will get returned.
				 */
				yy_c_buf_p = yytext;

				yy_act = YY_STATE_EOF((yy_start - 1) / 2);
				goto do_action;
				}

			    else
				YY_NEW_FILE;
			    }
			    break;

			case EOB_ACT_RESTART_SCAN:
			    yy_c_buf_p = yytext;
			    yy_hold_char = *yy_c_buf_p;
			    break;

			case EOB_ACT_LAST_MATCH:
			    yy_c_buf_p = &yy_ch_buf[yy_n_chars];

			    yy_current_state = yy_get_previous_state();

			    yy_cp = yy_c_buf_p;
			    yy_bp = yytext;
			    continue; /* go to "YY_DO_BEFORE_ACTION" */
			}
		    break;

		default:
		    printf( "action # %d\n", yy_act );
		    YY_FATAL_ERROR( "fatal flex scanner internal error" );
		}

	    break; /* exit bogus while loop */
	    }
	}
    }


/* yy_get_next_buffer - try to read in new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_RESTART_SCAN - restart the scanner
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register char *dest = yy_ch_buf;
    register char *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;
    
    if ( yy_c_buf_p != &yy_ch_buf[yy_n_chars + 1] )
	{
	YY_FATAL_ERROR( "NULL in input" );
	/*NOTREACHED*/
	}

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_eof_has_been_seen )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_BUF_SIZE - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	/* read in more data */
	YY_INPUT( (&yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    ret_val = EOB_ACT_END_OF_FILE;
	else
	    ret_val = EOB_ACT_LAST_MATCH;

	yy_eof_has_been_seen = 1;
	}

    else
	ret_val = EOB_ACT_RESTART_SCAN;

    yy_n_chars += number_to_move;
    yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in
     * yy_ch_buf; the first character is the one which
     * preceded it before reading in the latest buffer;
     * it needs to be kept around in case it's a
     * newline, so yy_get_previous_state() will have
     * with '^' rules active
     */

    yytext = &yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register char yy_c = yy_ec[*yy_cp];
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 121 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


#ifdef __STDC__
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif

    {
    register char *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char; /* undo effects of setting up yytext */

    if ( yy_cp < yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register char *dest = &yy_ch_buf[YY_BUF_SIZE + 2];
	register char *source = &yy_ch_buf[number_to_move];

	while ( source > yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;

	if ( yy_cp < yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


static int input()

    {
    int c;
    char *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{ /* need more input */
	yytext = yy_c_buf_p;
	++yy_c_buf_p;

	switch ( yy_get_next_buffer() )
	    {
	    /* this code, unfortunately, is somewhat redundant with
	     * that above
	     */
	    case EOB_ACT_END_OF_FILE:
		{
		if ( yywrap() )
		    {
		    yy_c_buf_p = yytext;
		    return ( EOF );
		    }

		yy_ch_buf[0] = '\n';
		yy_n_chars = 1;
		yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
		yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
		yy_eof_has_been_seen = 0;
		yytext = yy_c_buf_p = &yy_ch_buf[1];
		yy_hold_char = *yy_c_buf_p;

		return ( input() );
		}
		break;

	    case EOB_ACT_RESTART_SCAN:
		yy_c_buf_p = yytext;
		break;

	    case EOB_ACT_LAST_MATCH:
		YY_FATAL_ERROR( "unexpected last match in input()" );
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef __STDC__
static void yyrestart( FILE *input_file )
#else
static void yyrestart( input_file )
FILE *input_file;
#endif

    {
    if ( yyin != stdin )
	fclose( yyin );

    yyin = input_file;
    yy_init = 1;
    }
# line 80 "/home/maxamillion/byacc-14/cog_lex.txt"


yywrap()
{
	return(1);
}


int check_type()
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return(TYPE_NAME);
*
*	return(IDENTIFIER);
*/

/*
*	it actually will only return IDENTIFIER
*/

	return(IDENTIFIER);
}
