#include "cog.h"

#include "jk.h"
#include "types.h"

typedef struct sith_cog
{
} sith_cog;

enum COG_TYPE
{
    COG_TYPE_VERB    = 0,
    COG_TYPE_1       = 1,
    COG_TYPE_GLOBAL  = 2,
    COG_TYPE_MESSAGE  = 3
};

void* (*cog_alloc_symboltable)(int amt) = (void*)0x004FD050;
void (*cog_debug)(void) = (void*)0x004EE2F0;
void (*cog_deinit)(sith_cog* ctx) = (void*)0x004DE590;
void (*cog_exec)(sith_cog* ctx, int b) = (void*)0x004E2350;
void (*cog_register_global_message)(void* ctx, char* name, int id) = (void*)0x004E06C0;
void (*cog_register_message)(void* ctx, int msg, char* name) = (void*)0x004E0600;
int (*cog_register_msg_hander)(int a1, intptr_t a2, int a3, int a4) = (void*)0x4F2860;

void (*cog_activatebin)(sith_cog* ctx) = (void*)0x004E1520;
void (*cog_activateweapon)(sith_cog* ctx) = (void*)0x00507870;
void (*cog_adddynamicadd)(sith_cog* ctx) = (void*)0x005075F0;
void (*cog_adddynamicint)(sith_cog* ctx) = (void*)0x00507580;
void (*cog_addscoretoteam)(sith_cog* ctx) = (void*)0x004E1640;
void (*cog_addthingvel)(sith_cog* ctx) = (void*)0x00503300;
void (*cog_aiclearmode)(sith_cog* ctx) = (void*)0x00500FE0;
void (*cog_aiflee)(sith_cog* ctx) = (void*)0x00501420;
void (*cog_aigetmode)(sith_cog* ctx) = (void*)0x00500FA0;
void (*cog_aigetmovepos)(sith_cog* ctx) = (void*)0x00500F10;
void (*cog_aijump)(sith_cog* ctx) = (void*)0x00500D30;
void (*cog_aisetclass)(sith_cog* ctx) = (void*)0x00501490;
void (*cog_aisetfiretarget)(sith_cog* ctx) = (void*)0x005012C0;
void (*cog_aisetlookframe)(sith_cog* ctx) = (void*)0x00500EB0;
void (*cog_aisetlookpos)(sith_cog* ctx) = (void*)0x00500E60;
void (*cog_aisetmode)(sith_cog* ctx) = (void*)0x00500F50;
void (*cog_aisetmoveframe)(sith_cog* ctx) = (void*)0x00500DA0;
void (*cog_aisetmovepos)(sith_cog* ctx) = (void*)0x00500CD0;
void (*cog_aisetmovespeed)(sith_cog* ctx) = (void*)0x00500C60;
void (*cog_aisetmovething)(sith_cog* ctx) = (void*)0x00500E00;
void (*cog_amputatejoint)(sith_cog* ctx) = (void*)0x005045D0;
void (*cog_applyforce)(sith_cog* ctx) = (void*)0x00503290;
void (*cog_assignweapon)(sith_cog* ctx) = (void*)0x00507A10;
void (*cog_attachthingtosurf)(sith_cog* ctx) = (void*)0x00503520;
void (*cog_attachthingtothing)(sith_cog* ctx) = (void*)0x00503590;
void (*cog_attachthingtothingex)(sith_cog* ctx) = (void*)0x00503600;
void (*cog_autosavegame)(sith_cog* ctx) = (void*)0x00507E40;
void (*cog_autoselectweapon)(sith_cog* ctx) = (void*)0x00507A50;
void (*cog_bitclear)(sith_cog* ctx) = (void*)0x00506B50;
void (*cog_bitset)(sith_cog* ctx) = (void*)0x00506AF0;
void (*cog_bittest)(sith_cog* ctx) = (void*)0x00506B20;
void (*cog_capturething)(sith_cog* ctx) = (void*)0x00502E40;
void (*cog_changefirerate)(sith_cog* ctx) = (void*)0x00507DF0;
void (*cog_changeinv)(sith_cog* ctx) = (void*)0x00503080;
void (*cog_changesoundpitch)(sith_cog* ctx) = (void*)0x004FF9F0;
void (*cog_changesoundvol)(sith_cog* ctx) = (void*)0x004FF950;
void (*cog_clearXflags)(sith_cog* ctx) = (void*)0x00504F80;
void (*cog_clearadjoinflags)(sith_cog* ctx) = (void*)0x00500600;
void (*cog_cleardebugmodeflag)(sith_cog* ctx) = (void*)0x00506AB0;
void (*cog_clearfacetype)(sith_cog* ctx) = (void*)0x00500700;
void (*cog_cleargoalflags)(sith_cog* ctx) = (void*)0x004E0CC0;
void (*cog_clearmapmodeflag)(sith_cog* ctx) = (void*)0x00506F40;
void (*cog_clearmultimodeflags)(sith_cog* ctx) = (void*)0x00507C30;
void (*cog_clearphysicsflag)(sith_cog* ctx) = (void*)0x005047A0;
void (*cog_clearsectorflags)(sith_cog* ctx) = (void*)0x004FEDC0;
void (*cog_clearsubmodeflag)(sith_cog* ctx) = (void*)0x00506A50;
void (*cog_clearsurfaceflag)(sith_cog* ctx) = (void*)0x00500510;
void (*cog_clearthingattachflags)(sith_cog* ctx) = (void*)0x00504C80;
void (*cog_clearthingflags)(sith_cog* ctx) = (void*)0x00503B00;
void (*cog_copy_symboltable)(sith_cog* ctx) = (void*)0x004FCFD0;
void (*cog_createbackpack)(sith_cog* ctx) = (void*)0x004E12F0;
void (*cog_creatething)(sith_cog* ctx) = (void*)0x005020B0;
void (*cog_createthingatp)(sith_cog* ctx) = (void*)0x00502290;
void (*cog_createthingatposnr)(sith_cog* ctx) = (void*)0x005022A0;
void (*cog_createthingnr)(sith_cog* ctx) = (void*)0x00502150;
void (*cog_cyclecamera)(sith_cog* ctx) = (void*)0x00507100;
void (*cog_cyclecamera_internal)(sith_cog* ctx) = (void*)0x004C54D0;
void (*cog_damagething)(sith_cog* ctx) = (void*)0x00502430;
void (*cog_deactivatebin)(sith_cog* ctx) = (void*)0x004E1590;
void (*cog_deactivateweapon)(sith_cog* ctx) = (void*)0x005078D0;
void (*cog_destroything)(sith_cog* ctx) = (void*)0x00502600;
void (*cog_detachthing)(sith_cog* ctx) = (void*)0x00503490;
void (*cog_detachthing_internal)(sith_cog* ctx) = (void*)0x004CE380;
void (*cog_disableirmode)(sith_cog* ctx) = (void*)0x00506E90;
void (*cog_enableirmode)(sith_cog* ctx) = (void*)0x00506E50;
void (*cog_fireprojectile)(sith_cog* ctx) = (void*)0x00507650;
void (*cog_firstthinginsector)(sith_cog* ctx) = (void*)0x00503D10;
void (*cog_firstthinginview)(sith_cog* ctx) = (void*)0x00501030;
void (*cog_free_symboltable)(sith_cog* ctx) = (void*)0x004FD1C0;
void (*cog_freecoloreffect_modifycoloreffect)(sith_cog* ctx) = (void*)0x00507560;
void (*cog_getXflags)(sith_cog* ctx) = (void*)0x00504E60;
void (*cog_get_symbol)(sith_cog* ctx) = (void*)0x004FD380;
void (*cog_get_symbol_script_idx)(sith_cog* ctx) = (void*)0x004FD410;
void (*cog_getabsolutemax)(sith_cog* ctx) = (void*)0x004E0D90;
void (*cog_getactorweapon)(sith_cog* ctx) = (void*)0x00504680;
void (*cog_getajoinflags)(sith_cog* ctx) = (void*)0x00500660;
void (*cog_getattachflags_getthingattachflags)(sith_cog* ctx) = (void*)0x005034F0;
void (*cog_getautopickup)(sith_cog* ctx) = (void*)0x004E13B0;
void (*cog_getautoreload)(sith_cog* ctx) = (void*)0x004E1420;
void (*cog_getautoswitch)(sith_cog* ctx) = (void*)0x004E1340;
void (*cog_getcamerastate)(sith_cog* ctx) = (void*)0x00507BD0;
void (*cog_getceilingskyoffset)(sith_cog* ctx) = (void*)0x00500050;
void (*cog_getcollidetype)(sith_cog* ctx) = (void*)0x00503C80;
void (*cog_getcolormap)(sith_cog* ctx) = (void*)0x004FEB50;
void (*cog_getcurframe)(sith_cog* ctx) = (void*)0x00502BC0;
void (*cog_getcurinvweapon)(sith_cog* ctx) = (void*)0x00504160;
void (*cog_getcurrentcamera)(sith_cog* ctx) = (void*)0x005070B0;
void (*cog_getcurweapon)(sith_cog* ctx) = (void*)0x00507B90;
void (*cog_getcurweaponmode)(sith_cog* ctx) = (void*)0x00507B70;
void (*cog_getdebugmodeflag)(sith_cog* ctx) = (void*)0x00506AD0;
void (*cog_getdifficulty)(sith_cog* ctx) = (void*)0x00506A10;
void (*cog_getfacegeomode)(sith_cog* ctx) = (void*)0x00500820;
void (*cog_getfacelightmode)(sith_cog* ctx) = (void*)0x005008A0;
void (*cog_getfacetexmode)(sith_cog* ctx) = (void*)0x00500920;
void (*cog_getfacetype)(sith_cog* ctx) = (void*)0x00500760;
void (*cog_getflexgametime)(sith_cog* ctx) = (void*)0x005069F0;
void (*cog_getgametime)(sith_cog* ctx) = (void*)0x005069D0;
void (*cog_getgoalframe)(sith_cog* ctx) = (void*)0x00502C00;
void (*cog_getgravity)(sith_cog* ctx) = (void*)0x00506C40;
void (*cog_getheadlightin)(sith_cog* ctx) = (void*)0x00504050;
void (*cog_gethorizonskyoffset)(sith_cog* ctx) = (void*)0x004FFFD0;
void (*cog_getinv)(sith_cog* ctx) = (void*)0x00502FC0;
void (*cog_getinv_internal)(sith_cog* ctx) = (void*)0x004D1FC0;
void (*cog_getinvcog)(sith_cog* ctx) = (void*)0x005030F0;
void (*cog_getinvmax)(sith_cog* ctx) = (void*)0x00503E40;
void (*cog_getinvmin)(sith_cog* ctx) = (void*)0x00503DE0;
void (*cog_getkeylen)(sith_cog* ctx) = (void*)0x00506950;
void (*cog_getleveltime)(sith_cog* ctx) = (void*)0x00506B80;
void (*cog_getlifeleft)(sith_cog* ctx) = (void*)0x00504500;
void (*cog_getlocalplayer)(sith_cog* ctx) = (void*)0x004E0DA0;
void (*cog_getmajormode)(sith_cog* ctx) = (void*)0x005053B0;
void (*cog_getmapmodeflag)(sith_cog* ctx) = (void*)0x00506F20;
void (*cog_getmastercog)(sith_cog* ctx) = (void*)0x00507310;
void (*cog_getmaterialcel)(sith_cog* ctx) = (void*)0x00506E20;
void (*cog_getmaxplayers)(sith_cog* ctx) = (void*)0x004E0D70;
void (*cog_getmultimodeflags)(sith_cog* ctx) = (void*)0x00507C50;
void (*cog_getnumplayers)(sith_cog* ctx) = (void*)0x004E0D40;
void (*cog_getnumplayersinteam)(sith_cog* ctx) = (void*)0x004E15F0;
void (*cog_getnumsectorsurfaces)(sith_cog* ctx) = (void*)0x004FEF60;
void (*cog_getnusurfacevertices)(sith_cog* ctx) = (void*)0x004FFF00;
void (*cog_getparam)(sith_cog* ctx) = (void*)0x00506CA0;
void (*cog_getparticlegrowthspeed)(sith_cog* ctx) = (void*)0x00504D60;
void (*cog_getparticlesize)(sith_cog* ctx) = (void*)0x00504CE0;
void (*cog_getparticletimeoutrate)(sith_cog* ctx) = (void*)0x00504DE0;
void (*cog_getphysicsflag)(sith_cog* ctx) = (void*)0x005046F0;
void (*cog_getplayerkilled)(sith_cog* ctx) = (void*)0x004E1070;
void (*cog_getplayerkills)(sith_cog* ctx) = (void*)0x004E0FC0;
void (*cog_getplayernum)(sith_cog* ctx) = (void*)0x004E0E20;
void (*cog_getplayerscore)(sith_cog* ctx) = (void*)0x004E0F10;
void (*cog_getplayersuicide)(sith_cog* ctx) = (void*)0x004E1120;
void (*cog_getplayerteam)(sith_cog* ctx) = (void*)0x004E0E60;
void (*cog_getplayerthing)(sith_cog* ctx) = (void*)0x004E0DD0;
void (*cog_getprimaryfocus)(sith_cog* ctx) = (void*)0x00506FB0;
void (*cog_getrespawnmask)(sith_cog* ctx) = (void*)0x004E1490;
void (*cog_getscorelimit)(sith_cog* ctx) = (void*)0x00507DB0;
void (*cog_getsecondaryfocus)(sith_cog* ctx) = (void*)0x00507010;
void (*cog_getsectorcenter)(sith_cog* ctx) = (void*)0x004FEEF0;
void (*cog_getsectorcount)(sith_cog* ctx) = (void*)0x004FEED0;
void (*cog_getsectorflags)(sith_cog* ctx) = (void*)0x004FEE20;
void (*cog_getsectorint)(sith_cog* ctx) = (void*)0x004FE8A0;
void (*cog_getsectorlight)(sith_cog* ctx) = (void*)0x004FEA00;
void (*cog_getsectornumvertices)(sith_cog* ctx) = (void*)0x004FEF30;
void (*cog_getsectorplayercount)(sith_cog* ctx) = (void*)0x004FEE90;
void (*cog_getsectorsurfaceref)(sith_cog* ctx) = (void*)0x004FEFF0;
void (*cog_getsectorthingcount)(sith_cog* ctx) = (void*)0x004FEE50;
void (*cog_getsectorthrust)(sith_cog* ctx) = (void*)0x004FEC30;
void (*cog_getsectorvertexpos)(sith_cog* ctx) = (void*)0x004FEF90;
void (*cog_getselfcog)(sith_cog* ctx) = (void*)0x005072F0;
void (*cog_getsenderid)(sith_cog* ctx) = (void*)0x00505CB0;
void (*cog_getsenderref)(sith_cog* ctx) = (void*)0x00505CD0;
void (*cog_getsendertype)(sith_cog* ctx) = (void*)0x00505CF0;
void (*cog_getserfacesector)(sith_cog* ctx) = (void*)0x004FFEC0;
void (*cog_getsithmode)(sith_cog* ctx) = (void*)0x005069B0;
void (*cog_getsoundlen)(sith_cog* ctx) = (void*)0x004FFB00;
void (*cog_getsourceref)(sith_cog* ctx) = (void*)0x00505D10;
void (*cog_getsourcetype)(sith_cog* ctx) = (void*)0x00505D30;
void (*cog_getsubmodeflag)(sith_cog* ctx) = (void*)0x00506A70;
void (*cog_getsurfaceadjoin)(sith_cog* ctx) = (void*)0x004FFE80;
void (*cog_getsurfaceanim)(sith_cog* ctx) = (void*)0x00506180;
void (*cog_getsurfacecenter)(sith_cog* ctx) = (void*)0x00500A20;
void (*cog_getsurfacecount)(sith_cog* ctx) = (void*)0x00500A70;
void (*cog_getsurfaceflag)(sith_cog* ctx) = (void*)0x00500570;
void (*cog_getsurfacelight)(sith_cog* ctx) = (void*)0x005009F0;
void (*cog_getsurfacemat)(sith_cog* ctx) = (void*)0x005003C0;
void (*cog_getsurfacenormal)(sith_cog* ctx) = (void*)0x00500AA0;
void (*cog_getsurfacevertexpos)(sith_cog* ctx) = (void*)0x004FFF30;
void (*cog_getteamscore)(sith_cog* ctx) = (void*)0x00507CD0;
void (*cog_getthingcapturecog)(sith_cog* ctx) = (void*)0x00504B50;
void (*cog_getthingclasscog)(sith_cog* ctx) = (void*)0x00504AE0;
void (*cog_getthingcollidesize)(sith_cog* ctx) = (void*)0x005051C0;
void (*cog_getthingcount)(sith_cog* ctx) = (void*)0x00506BC0;
void (*cog_getthingcurgeomode)(sith_cog* ctx) = (void*)0x00504320;
void (*cog_getthingcurlightmode)(sith_cog* ctx) = (void*)0x00504380;
void (*cog_getthingcurtexmode)(sith_cog* ctx) = (void*)0x005043E0;
void (*cog_getthingfireoffset)(sith_cog* ctx) = (void*)0x005050C0;
void (*cog_getthingflags)(sith_cog* ctx) = (void*)0x00503A70;
void (*cog_getthinghealth_gethealth)(sith_cog* ctx) = (void*)0x00502570;
void (*cog_getthinglight)(sith_cog* ctx) = (void*)0x00502990;
void (*cog_getthinglightmode)(sith_cog* ctx) = (void*)0x00504230;
void (*cog_getthinglook)(sith_cog* ctx) = (void*)0x00504A10;
void (*cog_getthinglvec)(sith_cog* ctx) = (void*)0x00503390;
void (*cog_getthingmass)(sith_cog* ctx) = (void*)0x005052A0;
void (*cog_getthingmode)(sith_cog* ctx) = (void*)0x005041D0;
void (*cog_getthingmodel)(sith_cog* ctx) = (void*)0x005039B0;
void (*cog_getthingmovesize)(sith_cog* ctx) = (void*)0x00505230;
void (*cog_getthingparent)(sith_cog* ctx) = (void*)0x00502EB0;
void (*cog_getthingparent_internal)(sith_cog* ctx) = (void*)0x004CC6A0;
void (*cog_getthingrespawn)(sith_cog* ctx) = (void*)0x00504BC0;
void (*cog_getthingrotvel)(sith_cog* ctx) = (void*)0x005049D0;
void (*cog_getthingrvec)(sith_cog* ctx) = (void*)0x00503410;
void (*cog_getthingsector)(sith_cog* ctx) = (void*)0x00502B80;
void (*cog_getthingsignature)(sith_cog* ctx) = (void*)0x00504BF0;
void (*cog_getthingtemplate)(sith_cog* ctx) = (void*)0x00504440;
void (*cog_getthingtemplatecount)(sith_cog* ctx) = (void*)0x00506BE0;
void (*cog_getthingtexmode)(sith_cog* ctx) = (void*)0x00504290;
void (*cog_getthingthrust)(sith_cog* ctx) = (void*)0x005045A0;
void (*cog_getthingtype)(sith_cog* ctx) = (void*)0x00502080;
void (*cog_getthinguserdata)(sith_cog* ctx) = (void*)0x00505150;
void (*cog_getthinguvec)(sith_cog* ctx) = (void*)0x005033D0;
void (*cog_getthingvel)(sith_cog* ctx) = (void*)0x00503160;
void (*cog_gettimelimit)(sith_cog* ctx) = (void*)0x00507D40;
void (*cog_getwallcel)(sith_cog* ctx) = (void*)0x00500300;
void (*cog_getweaponprior)(sith_cog* ctx) = (void*)0x00507AE0;
void (*cog_haslos)(sith_cog* ctx) = (void*)0x00505060;
void (*cog_healthing)(sith_cog* ctx) = (void*)0x00502500;
void (*cog_heapfree)(sith_cog* ctx) = (void*)0x005072C0;
void (*cog_heapget)(sith_cog* ctx) = (void*)0x00507250;
void (*cog_heapnew)(sith_cog* ctx) = (void*)0x00507180;
void (*cog_heapset)(sith_cog* ctx) = (void*)0x005071F0;
void (*cog_isaitargetinsight)(sith_cog* ctx) = (void*)0x005013C0;
void (*cog_isinvactivated)(sith_cog* ctx) = (void*)0x004E0B80;
void (*cog_isinvactivated_internal)(sith_cog* ctx) = (void*)0x004D2110;
void (*cog_isinvavailable)(sith_cog* ctx) = (void*)0x004E0BE0;
void (*cog_isinvavailable_internal)(sith_cog* ctx) = (void*)0x004D21A0;
void (*cog_ismulti)(sith_cog* ctx) = (void*)0x00507C70;
void (*cog_isserver)(sith_cog* ctx) = (void*)0x00507CA0;
void (*cog_isthingcrouching_iscrouching)(sith_cog* ctx) = (void*)0x00504A90;
void (*cog_isthingmoving_ismoving)(sith_cog* ctx) = (void*)0x00502CB0;
void (*cog_isthingvisible)(sith_cog* ctx) = (void*)0x005040A0;
void (*cog_jkclearflags)(sith_cog* ctx) = (void*)0x0040A450;
void (*cog_jkclearsuperflags)(sith_cog* ctx) = (void*)0x0040A9E0;
void (*cog_jkdisablesaber)(sith_cog* ctx) = (void*)0x0040AB20;
void (*cog_jkenablesaber)(sith_cog* ctx) = (void*)0x0040AAA0;
void (*cog_jkendlevel)(sith_cog* ctx) = (void*)0x0040A580;
void (*cog_jkendtarget)(sith_cog* ctx) = (void*)0x0040AD20;
void (*cog_jkgetchoice)(sith_cog* ctx) = (void*)0x0040B3D0;
void (*cog_jkgetflags)(sith_cog* ctx) = (void*)0x0040A4C0;
void (*cog_jkgetsabercam)(sith_cog* ctx) = (void*)0x0040B3B0;
void (*cog_jkgetsuperflags)(sith_cog* ctx) = (void*)0x0040AA50;
void (*cog_jkplaypovkey)(sith_cog* ctx) = (void*)0x0040A620;
void (*cog_jkprintunistring)(sith_cog* ctx) = (void*)0x0040A800;
void (*cog_jksetflags)(sith_cog* ctx) = (void*)0x0040A3E0;
void (*cog_jksetforcespeed)(sith_cog* ctx) = (void*)0x0040A710;
void (*cog_jksetinvis)(sith_cog* ctx) = (void*)0x0040A730;
void (*cog_jksetinvulnerable)(sith_cog* ctx) = (void*)0x0040A7A0;
void (*cog_jksetpersuasioninfo)(sith_cog* ctx) = (void*)0x0040AC90;
void (*cog_jksetpovmodel)(sith_cog* ctx) = (void*)0x0040A5D0;
void (*cog_jksetsaberinfo)(sith_cog* ctx) = (void*)0x0040ABA0;
void (*cog_jksetsuperflags)(sith_cog* ctx) = (void*)0x0040A970;
void (*cog_jksettarget)(sith_cog* ctx) = (void*)0x0040AD00;
void (*cog_jksettargetcolors)(sith_cog* ctx) = (void*)0x0040AD30;
void (*cog_jksetwaggle)(sith_cog* ctx) = (void*)0x0040AB50;
void (*cog_jksetweaponmesh)(sith_cog* ctx) = (void*)0x0040A4F0;
void (*cog_jkstoppovkey)(sith_cog* ctx) = (void*)0x0040A6B0;
void (*cog_jkstringclear)(sith_cog* ctx) = (void*)0x0040AD80;
void (*cog_jkstringconcatasciistring)(sith_cog* ctx) = (void*)0x0040AE30;
void (*cog_jkstringconcatflex)(sith_cog* ctx) = (void*)0x0040B090;
void (*cog_jkstringconcatformattedflex)(sith_cog* ctx) = (void*)0x0040B100;
void (*cog_jkstringconcatformattedint)(sith_cog* ctx) = (void*)0x0040AFE0;
void (*cog_jkstringconcatint)(sith_cog* ctx) = (void*)0x0040AF70;
void (*cog_jkstringconcatplayername)(sith_cog* ctx) = (void*)0x0040AEB0;
void (*cog_jkstringconcatspace)(sith_cog* ctx) = (void*)0x0040AF10;
void (*cog_jkstringconcatunistring)(sith_cog* ctx) = (void*)0x0040ADA0;
void (*cog_jkstringconcatvector)(sith_cog* ctx) = (void*)0x0040B1C0;
void (*cog_jkstringoutput)(sith_cog* ctx) = (void*)0x0040B270;
void (*cog_jumptoframe)(sith_cog* ctx) = (void*)0x00502650;
void (*cog_killtimerex)(sith_cog* ctx) = (void*)0x00506470;
void (*cog_lex_addsymbol)(sith_cog* ctx) = (void*)0x004FD7F0;
void (*cog_lex_flex_scanner)(sith_cog* ctx) = (void*)0x0050D260;
void (*cog_lex_get_sym)(sith_cog* ctx) = (void*)0x004FD650;
void (*cog_lex_scan_vector3)(sith_cog* ctx) = (void*)0x004FD8E0;
void (*cog_loadkeyframe)(sith_cog* ctx) = (void*)0x00506200;
void (*cog_loadmodel)(sith_cog* ctx) = (void*)0x00506240;
void (*cog_loadsound)(sith_cog* ctx) = (void*)0x004FF880;
void (*cog_loadtemplate)(sith_cog* ctx) = (void*)0x005061C0;
void (*cog_materialanim)(sith_cog* ctx) = (void*)0x00506030;
void (*cog_message_related)(sith_cog* ctx) = (void*)0x004DEBE0;
void (*cog_movetoframe)(sith_cog* ctx) = (void*)0x00502720;
void (*cog_newcoloreffect)(sith_cog* ctx) = (void*)0x00507360;
void (*cog_nextthinginsector)(sith_cog* ctx) = (void*)0x00503D60;
void (*cog_nextthinginview)(sith_cog* ctx) = (void*)0x00501150;
void (*cog_nthbackpackbin)(sith_cog* ctx) = (void*)0x004E1210;
void (*cog_nthbackpackvalue)(sith_cog* ctx) = (void*)0x004E1260;
void (*cog_numbackpackitems)(sith_cog* ctx) = (void*)0x004E12B0;
void (*cog_parsearg)(sith_cog* ctx) = (void*)0x005048D0;
void (*cog_parser_addleaf)(sith_cog* ctx) = (void*)0x004FD450;
void (*cog_parser_addleaf_vector)(sith_cog* ctx) = (void*)0x004FD4F0;
void (*cog_parser_addlinkingnode)(sith_cog* ctx) = (void*)0x004FD5A0;
void (*cog_pathmovepause)(sith_cog* ctx) = (void*)0x00503FA0;
void (*cog_pathmoveresume)(sith_cog* ctx) = (void*)0x005040E0;
void (*cog_pickupbackpack)(sith_cog* ctx) = (void*)0x004E11C0;
void (*cog_playkey)(sith_cog* ctx) = (void*)0x00503740;
void (*cog_playmode)(sith_cog* ctx) = (void*)0x00503680;
void (*cog_playsong)(sith_cog* ctx) = (void*)0x004FF160;
void (*cog_playsound_internal)(sith_cog* ctx) = (void*)0x004DB4F0;
void (*cog_playsoundclass)(sith_cog* ctx) = (void*)0x004FF8C0;
void (*cog_playsoundclass_internal1)(sith_cog* ctx) = (void*)0x004E6B70;
void (*cog_playsoundclass_internal_multi)(sith_cog* ctx) = (void*)0x004F3960;
void (*cog_playsoundglobal)(sith_cog* ctx) = (void*)0x004FF6A0;
void (*cog_playsoundlocal)(sith_cog* ctx) = (void*)0x004FF5B0;
void (*cog_playsoundpos)(sith_cog* ctx) = (void*)0x004FF400;
void (*cog_playsoundpos_internal)(sith_cog* ctx) = (void*)0x004DB880;
void (*cog_playsoundthing)(sith_cog* ctx) = (void*)0x004FF1B0;
void (*cog_pop_arg_as_float)(sith_cog* ctx) = (void*)0x004E24F0;
void (*cog_pop_arg_as_int)(sith_cog* ctx) = (void*)0x004E25C0;
void (*cog_pop_arg_as_mat)(sith_cog* ctx) = (void*)0x004E2DB0;
void (*cog_pop_arg_as_sector)(sith_cog* ctx) = (void*)0x004E2BD0;
void (*cog_pop_arg_as_sound)(sith_cog* ctx) = (void*)0x004E2AD0;
void (*cog_pop_arg_as_str)(sith_cog* ctx) = (void*)0x004E3260;
void (*cog_pop_arg_as_surface)(sith_cog* ctx) = (void*)0x004E2CC0;
void (*cog_pop_arg_as_thing)(sith_cog* ctx) = (void*)0x004E28C0;
void (*cog_pop_arg_as_thing_other)(sith_cog* ctx) = (void*)0x004E29C0;
void (*cog_pop_value)(sith_cog* ctx) = (void*)0x004E2440;
void (*cog_pop_vector3)(sith_cog* ctx) = (void*)0x004E26E0;
void (*cog_prevthinginseector)(sith_cog* ctx) = (void*)0x00503DA0;
void (*cog_print)(sith_cog* ctx) = (void*)0x00505E80;
void (*cog_printflex)(sith_cog* ctx) = (void*)0x00505F70;
void (*cog_printint)(sith_cog* ctx) = (void*)0x00505EA0;
void (*cog_printvector)(sith_cog* ctx) = (void*)0x00505EE0;
void (*cog_rand)(sith_cog* ctx) = (void*)0x00505D50;
void (*cog_randvec)(sith_cog* ctx) = (void*)0x00505D80;
void (*cog_releasething)(sith_cog* ctx) = (void*)0x00502E70;
void (*cog_reset)(sith_cog* ctx) = (void*)0x005064E0;
void (*cog_return_float)(sith_cog* ctx) = (void*)0x004E33C0;
void (*cog_return_val)(sith_cog* ctx) = (void*)0x004E3340;
void (*cog_return_vector3)(sith_cog* ctx) = (void*)0x004E3450;
void (*cog_returnex)(sith_cog* ctx) = (void*)0x00506C80;
void (*cog_rotate)(sith_cog* ctx) = (void*)0x00502950;
void (*cog_rotatepivot)(sith_cog* ctx) = (void*)0x00502880;
void (*cog_sectorsound)(sith_cog* ctx) = (void*)0x004FFA60;
void (*cog_selectweapon)(sith_cog* ctx) = (void*)0x005079D0;
void (*cog_sendmessage)(sith_cog* ctx) = (void*)0x00506850;
void (*cog_sendmessageex)(sith_cog* ctx) = (void*)0x005068A0;
void (*cog_sendtrigger)(sith_cog* ctx) = (void*)0x00507730;
void (*cog_setXflags)(sith_cog* ctx) = (void*)0x00504EF0;
void (*cog_setactorextras)(sith_cog* ctx) = (void*)0x00504410;
void (*cog_setactorweapon)(sith_cog* ctx) = (void*)0x00504620;
void (*cog_setadjoinflags)(sith_cog* ctx) = (void*)0x005005A0;
void (*cog_setarmedmode)(sith_cog* ctx) = (void*)0x00503A00;
void (*cog_setautopickup)(sith_cog* ctx) = (void*)0x004E13F0;
void (*cog_setautoreload)(sith_cog* ctx) = (void*)0x004E1460;
void (*cog_setautoswitch)(sith_cog* ctx) = (void*)0x004E1380;
void (*cog_setbinwait)(sith_cog* ctx) = (void*)0x004E1690;
void (*cog_setcamerafocus)(sith_cog* ctx) = (void*)0x00506F60;
void (*cog_setcamerafocus_internal)(sith_cog* ctx) = (void*)0x004C5670;
void (*cog_setcamerastate)(sith_cog* ctx) = (void*)0x00507BF0;
void (*cog_setceilingskyoffset)(sith_cog* ctx) = (void*)0x00500010;
void (*cog_setcollidetype)(sith_cog* ctx) = (void*)0x00503CB0;
void (*cog_setcolormap)(sith_cog* ctx) = (void*)0x004FEBB0;
void (*cog_setcurinvweapon)(sith_cog* ctx) = (void*)0x00504130;
void (*cog_setcurrentcamera)(sith_cog* ctx) = (void*)0x00507070;
void (*cog_setcurrentcamera_internal)(sith_cog* ctx) = (void*)0x004C5420;
void (*cog_setcurweapon)(sith_cog* ctx) = (void*)0x00507AA0;
void (*cog_setdebugmodeflag)(sith_cog* ctx) = (void*)0x00506A90;
void (*cog_setfacegeomode)(sith_cog* ctx) = (void*)0x00500790;
void (*cog_setfacelightmode)(sith_cog* ctx) = (void*)0x00500850;
void (*cog_setfacetexmode)(sith_cog* ctx) = (void*)0x005008D0;
void (*cog_setfacetype)(sith_cog* ctx) = (void*)0x005006A0;
void (*cog_setfirewait)(sith_cog* ctx) = (void*)0x00507930;
void (*cog_setgoalflags)(sith_cog* ctx) = (void*)0x004E0C40;
void (*cog_setgravity)(sith_cog* ctx) = (void*)0x00506C60;
void (*cog_setheadlightintensity)(sith_cog* ctx) = (void*)0x00503FF0;
void (*cog_sethorizonskyoffset)(sith_cog* ctx) = (void*)0x004FFF90;
void (*cog_setinv)(sith_cog* ctx) = (void*)0x00503020;
void (*cog_setinvactivate)(sith_cog* ctx) = (void*)0x004E0AA0;
void (*cog_setinvavailable)(sith_cog* ctx) = (void*)0x004E0B10;
void (*cog_setinvflags)(sith_cog* ctx) = (void*)0x00506EA0;
void (*cog_setlifeleft)(sith_cog* ctx) = (void*)0x00504480;
void (*cog_setmapmodeflags)(sith_cog* ctx) = (void*)0x00506F00;
void (*cog_setmastercog)(sith_cog* ctx) = (void*)0x00507340;
void (*cog_setmaterialcel)(sith_cog* ctx) = (void*)0x00506DE0;
void (*cog_setmountwait)(sith_cog* ctx) = (void*)0x00507980;
void (*cog_setmultimodeflags)(sith_cog* ctx) = (void*)0x00507C10;
void (*cog_setmusicvol)(sith_cog* ctx) = (void*)0x004FFAA0;
void (*cog_setparam)(sith_cog* ctx) = (void*)0x00506CE0;
void (*cog_setparticlegrowthspeed)(sith_cog* ctx) = (void*)0x00504DA0;
void (*cog_setparticlesize)(sith_cog* ctx) = (void*)0x00504D20;
void (*cog_setparticletimeoutrate)(sith_cog* ctx) = (void*)0x00504E20;
void (*cog_setphysicsflag)(sith_cog* ctx) = (void*)0x00504730;
void (*cog_setplayerkilled)(sith_cog* ctx) = (void*)0x004E10C0;
void (*cog_setplayerkills)(sith_cog* ctx) = (void*)0x004E1010;
void (*cog_setplayerscore)(sith_cog* ctx) = (void*)0x004E0F60;
void (*cog_setplayersuicide)(sith_cog* ctx) = (void*)0x004E1170;
void (*cog_setplayerteam)(sith_cog* ctx) = (void*)0x004E0EB0;
void (*cog_setpovshake)(sith_cog* ctx) = (void*)0x00507110;
void (*cog_setpulse)(sith_cog* ctx) = (void*)0x00506280;
void (*cog_setrespawnmask)(sith_cog* ctx) = (void*)0x004E14E0;
void (*cog_setscorelimit)(sith_cog* ctx) = (void*)0x00507DD0;
void (*cog_setsectoradjoins_sectoradjoins)(sith_cog* ctx) = (void*)0x004FEAD0;
void (*cog_setsectorflags)(sith_cog* ctx) = (void*)0x004FED60;
void (*cog_setsectorint)(sith_cog* ctx) = (void*)0x004FE8F0;
void (*cog_setsectorlight_sectorlight)(sith_cog* ctx) = (void*)0x004FEA30;
void (*cog_setsectorthrust)(sith_cog* ctx) = (void*)0x004FEC70;
void (*cog_setsubmodeflag)(sith_cog* ctx) = (void*)0x00506A30;
void (*cog_setsurfaceflag)(sith_cog* ctx) = (void*)0x005004B0;
void (*cog_setsurfacelight)(sith_cog* ctx) = (void*)0x00500950;
void (*cog_setsurfacemat)(sith_cog* ctx) = (void*)0x00500410;
void (*cog_setteamscore)(sith_cog* ctx) = (void*)0x00507D10;
void (*cog_setthingattachflags)(sith_cog* ctx) = (void*)0x00504C20;
void (*cog_setthingcapturecog)(sith_cog* ctx) = (void*)0x00504B90;
void (*cog_setthingclasscog)(sith_cog* ctx) = (void*)0x00504B20;
void (*cog_setthingcollidesize)(sith_cog* ctx) = (void*)0x00505200;
void (*cog_setthingcurgeomode)(sith_cog* ctx) = (void*)0x005042C0;
void (*cog_setthingcurlightmode)(sith_cog* ctx) = (void*)0x00504350;
void (*cog_setthingcurtexmode)(sith_cog* ctx) = (void*)0x005043B0;
void (*cog_setthingfireoffset)(sith_cog* ctx) = (void*)0x00505100;
void (*cog_setthingflags)(sith_cog* ctx) = (void*)0x00503AA0;
void (*cog_setthinghealth_sethealth)(sith_cog* ctx) = (void*)0x005025C0;
void (*cog_setthinglightmode)(sith_cog* ctx) = (void*)0x00504200;
void (*cog_setthingmass)(sith_cog* ctx) = (void*)0x005052E0;
void (*cog_setthingmode)(sith_cog* ctx) = (void*)0x005041A0;
void (*cog_setthingmodel)(sith_cog* ctx) = (void*)0x00503920;
void (*cog_setthingmovesize)(sith_cog* ctx) = (void*)0x00505270;
void (*cog_setthingpulse)(sith_cog* ctx) = (void*)0x00502D60;
void (*cog_setthingrotvel)(sith_cog* ctx) = (void*)0x00504950;
void (*cog_setthingtexmode)(sith_cog* ctx) = (void*)0x00504260;
void (*cog_setthingthrust)(sith_cog* ctx) = (void*)0x00504540;
void (*cog_setthingtimer)(sith_cog* ctx) = (void*)0x00502DD0;
void (*cog_setthingtype)(sith_cog* ctx) = (void*)0x00503C50;
void (*cog_setthinguserdata)(sith_cog* ctx) = (void*)0x00505190;
void (*cog_setthingvel)(sith_cog* ctx) = (void*)0x00503210;
void (*cog_settimelimit)(sith_cog* ctx) = (void*)0x00507D80;
void (*cog_settimer)(sith_cog* ctx) = (void*)0x00506340;
void (*cog_settimerex)(sith_cog* ctx) = (void*)0x005063F0;
void (*cog_setwallcel)(sith_cog* ctx) = (void*)0x00500340;
void (*cog_skilltarget)(sith_cog* ctx) = (void*)0x005047E0;
void (*cog_skiptoframe)(sith_cog* ctx) = (void*)0x005027D0;
void (*cog_sleep)(sith_cog* ctx) = (void*)0x00505E00;
void (*cog_slideceilingsky)(sith_cog* ctx) = (void*)0x00500100;
void (*cog_slidehorizonsky)(sith_cog* ctx) = (void*)0x00500090;
void (*cog_slidewall_slidesurface)(sith_cog* ctx) = (void*)0x00500220;
void (*cog_stopanim)(sith_cog* ctx) = (void*)0x005060E0;
void (*cog_stopkey)(sith_cog* ctx) = (void*)0x00503870;
void (*cog_stopsound)(sith_cog* ctx) = (void*)0x004FF7D0;
void (*cog_stopsurfaceanim)(sith_cog* ctx) = (void*)0x00506130;
void (*cog_stopthing)(sith_cog* ctx) = (void*)0x00502C40;
void (*cog_surfaceanim)(sith_cog* ctx) = (void*)0x00505FB0;
void (*cog_surfacelightanim)(sith_cog* ctx) = (void*)0x00500170;
void (*cog_syncscores)(sith_cog* ctx) = (void*)0x004E16F0;
void (*cog_syncsector)(sith_cog* ctx) = (void*)0x004FF040;
void (*cog_syncsurface)(sith_cog* ctx) = (void*)0x00500AE0;
void (*cog_syncthingattachment)(sith_cog* ctx) = (void*)0x00505360;
void (*cog_syncthingattachment_internal)(sith_cog* ctx) = (void*)0x004F4E80;
void (*cog_syncthingpos)(sith_cog* ctx) = (void*)0x00505340;
void (*cog_syncthingpos_internal)(sith_cog* ctx) = (void*)0x004CF560;
void (*cog_syncthingstate)(sith_cog* ctx) = (void*)0x00505390;
void (*cog_takeitem)(sith_cog* ctx) = (void*)0x00505020;
void (*cog_teleportthing)(sith_cog* ctx) = (void*)0x00503B60;
void (*cog_thinglightanim)(sith_cog* ctx) = (void*)0x00502A60;
void (*cog_thingviewdot)(sith_cog* ctx) = (void*)0x005011A0;
void (*cog_vectoradd)(sith_cog* ctx) = (void*)0x00506550;
void (*cog_vectorcross)(sith_cog* ctx) = (void*)0x00506670;
void (*cog_vectordist)(sith_cog* ctx) = (void*)0x005067D0;
void (*cog_vectordot)(sith_cog* ctx) = (void*)0x00506610;
void (*cog_vectorlen)(sith_cog* ctx) = (void*)0x00506700;
void (*cog_vectornorm)(sith_cog* ctx) = (void*)0x506DA0;
void (*cog_vectorscale)(sith_cog* ctx) = (void*)0x00506760;
void (*cog_vectorset)(sith_cog* ctx) = (void*)0x005064F0;
void (*cog_vectorsub)(sith_cog* ctx) = (void*)0x005065B0;
void (*cog_vectorx)(sith_cog* ctx) = (void*)0x00506D10;
void (*cog_vectory)(sith_cog* ctx) = (void*)0x00506D40;
void (*cog_vectorz)(sith_cog* ctx) = (void*)0x00506D70;
void (*cog_waitforstop)(sith_cog* ctx) = (void*)0x502B10;
void (*cog_setthinglight_thinglight)(sith_cog* ctx) = (void*)0x5029D0;
void (*cog_getthingpos)(sith_cog* ctx) = (void*)0x502EF0;
void (*cog_setthingpos)(sith_cog* ctx) = (void*)0x502F30;


void cog_register_jk_verbs()
{
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_getlocalplayer, "jkgetlocalplayer");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetflags, "jksetflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkgetflags, "jkgetflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkclearflags, "jkclearflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkendlevel, "jkendlevel");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkprintunistring, "jkprintunistring");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetpovmodel, "jksetpovmodel");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkplaypovkey, "jkplaypovkey");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstoppovkey, "jkstoppovkey");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetweaponmesh, "jksetweaponmesh");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkenablesaber, "jkenablesaber");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkdisablesaber, "jkdisablesaber");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetsaberinfo, "jksetsaberinfo");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetpersuasioninfo, "jksetpersuasion");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetforcespeed, "jksetforcespeed");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetinvis, "jksetinvis");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetinvulnerable, "jksetinvulnerable");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetwaggle, "jksetwaggle");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksetsuperflags, "jksetsuperflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkclearsuperflags, "jkclearsuperflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkgetsuperflags, "jkgetsuperflags");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksettarget, "jksettarget");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkendtarget, "jkendtarget");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jksettargetcolors, "jksettargetcolors");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringclear, "jkstringclear");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatspace, "jkstringconcatspace");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatunistring, "jkstringconcatunistring");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatasciistring, "jkstringconcatasciistring");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatplayername, "jkstringconcatplayername");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatint, "jkstringconcatint");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatformattedint, "jkstringconcatformattedint");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatflex, "jkstringconcatflex");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatformattedflex, "jkstringconcatformattedflex");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringconcatvector, "jkstringconcatvector");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkstringoutput, "jkstringoutput");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkgetsabercam, "jkgetsabercam");
    cog_verb_register(g_cog_symboltable_hashmap, (intptr_t)cog_jkgetchoice, "jkgetchoice");
}

int cog_jk_init()
{
    cog_register_jk_verbs();
    //cog_jk_initted = 1; //553FB0
    return 1;
}

void cog_math_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_sleep, "sleep");
    cog_verb_register(a1, (intptr_t)cog_rand, "rand");
    cog_verb_register(a1, (intptr_t)cog_randvec, "randvec");
    cog_verb_register(a1, (intptr_t)cog_getsenderref, "getsenderref");
    cog_verb_register(a1, (intptr_t)cog_getsendertype, "getsendertype");
    cog_verb_register(a1, (intptr_t)cog_getsenderid, "getsenderid");
    cog_verb_register(a1, (intptr_t)cog_getsourcetype, "getsourcetype");
    cog_verb_register(a1, (intptr_t)cog_getsourceref, "getsourceref");
    cog_verb_register(a1, (intptr_t)cog_getthingcount, "getthingcount");
    cog_verb_register(a1, (intptr_t)cog_getgravity, "getgravity");
    cog_verb_register(a1, (intptr_t)cog_setgravity, "setgravity");
    cog_verb_register(a1, (intptr_t)cog_getleveltime, "getleveltime");
    cog_verb_register(a1, (intptr_t)cog_getgametime, "getgametime");
    cog_verb_register(a1, (intptr_t)cog_getflexgametime, "getflexgametime");
    cog_verb_register(a1, (intptr_t)cog_getthingtemplatecount, "getthingtemplatecount");
    cog_verb_register(a1, (intptr_t)cog_setpulse, "setpulse");
    cog_verb_register(a1, (intptr_t)cog_settimer, "settimer");
    cog_verb_register(a1, (intptr_t)cog_settimerex, "settimerex");
    cog_verb_register(a1, (intptr_t)cog_killtimerex, "killtimerex");
    cog_verb_register(a1, (intptr_t)cog_reset, "reset");
    cog_verb_register(a1, (intptr_t)cog_materialanim, "materialanim");
    cog_verb_register(a1, (intptr_t)cog_stopanim, "stopanim");
    cog_verb_register(a1, (intptr_t)cog_stopsurfaceanim, "stopsurfaceanim");
    cog_verb_register(a1, (intptr_t)cog_getsurfaceanim, "getsurfaceanim");
    cog_verb_register(a1, (intptr_t)cog_surfaceanim, "surfaceanim");
    cog_verb_register(a1, (intptr_t)cog_getkeylen, "getkeylen");
    cog_verb_register(a1, (intptr_t)cog_loadtemplate, "loadtemplate");
    cog_verb_register(a1, (intptr_t)cog_loadkeyframe, "loadkeyframe");
    cog_verb_register(a1, (intptr_t)cog_loadmodel, "loadmodel");
    cog_verb_register(a1, (intptr_t)cog_print, "print");
    cog_verb_register(a1, (intptr_t)cog_printint, "printint");
    cog_verb_register(a1, (intptr_t)cog_printflex, "printflex");
    cog_verb_register(a1, (intptr_t)cog_printvector, "printvector");
    cog_verb_register(a1, (intptr_t)cog_vectoradd, "vectoradd");
    cog_verb_register(a1, (intptr_t)cog_vectorsub, "vectorsub");
    cog_verb_register(a1, (intptr_t)cog_vectordot, "vectordot");
    cog_verb_register(a1, (intptr_t)cog_vectorcross, "vectorcross");
    cog_verb_register(a1, (intptr_t)cog_vectorset, "vectorset");
    cog_verb_register(a1, (intptr_t)cog_vectorlen, "vectorlen");
    cog_verb_register(a1, (intptr_t)cog_vectorscale, "vectorscale");
    cog_verb_register(a1, (intptr_t)cog_vectordist, "vectordist");
    cog_verb_register(a1, (intptr_t)cog_vectorx, "vectorx");
    cog_verb_register(a1, (intptr_t)cog_vectory, "vectory");
    cog_verb_register(a1, (intptr_t)cog_vectorz, "vectorz");
    cog_verb_register(a1, (intptr_t)cog_vectornorm, "vectornorm");
    cog_verb_register(a1, (intptr_t)cog_getsithmode, "getsithmode");
    cog_verb_register(a1, (intptr_t)cog_getdifficulty, "getdifficulty");
    cog_verb_register(a1, (intptr_t)cog_setsubmodeflag, "setsubmodeflag");
    cog_verb_register(a1, (intptr_t)cog_getsubmodeflag, "getsubmodeflag");
    cog_verb_register(a1, (intptr_t)cog_clearsubmodeflag, "clearsubmodeflag");
    cog_verb_register(a1, (intptr_t)cog_setdebugmodeflag, "setdebugmodeflag");
    cog_verb_register(a1, (intptr_t)cog_getdebugmodeflag, "getdebugmodeflag");
    cog_verb_register(a1, (intptr_t)cog_cleardebugmodeflag, "cleardebugmodeflag");
    cog_verb_register(a1, (intptr_t)cog_bitset, "bitset");
    cog_verb_register(a1, (intptr_t)cog_bittest, "bittest");
    cog_verb_register(a1, (intptr_t)cog_bitclear, "bitclear");
    cog_verb_register(a1, (intptr_t)cog_fireprojectile, "fireprojectile");
    cog_verb_register(a1, (intptr_t)cog_activateweapon, "activateweapon");
    cog_verb_register(a1, (intptr_t)cog_deactivateweapon, "deactivateweapon");
    cog_verb_register(a1, (intptr_t)cog_setmountwait, "setmountwait");
    cog_verb_register(a1, (intptr_t)cog_setfirewait, "setfirewait");
    cog_verb_register(a1, (intptr_t)cog_selectweapon, "selectweapon");
    cog_verb_register(a1, (intptr_t)cog_assignweapon, "assignweapon");
    cog_verb_register(a1, (intptr_t)cog_autoselectweapon, "autoselectweapon");
    cog_verb_register(a1, (intptr_t)cog_getweaponprior, "getweaponprior");
    cog_verb_register(a1, (intptr_t)cog_setcurweapon, "setcurweapon");
    cog_verb_register(a1, (intptr_t)cog_getcurweapon, "getcurweapon");
    cog_verb_register(a1, (intptr_t)cog_getcurweaponmode, "getcurweaponmode");
    cog_verb_register(a1, (intptr_t)cog_changefirerate, "changefirerate");
    cog_verb_register(a1, (intptr_t)cog_sendmessage, "sendmessage");
    cog_verb_register(a1, (intptr_t)cog_sendmessageex, "sendmessageex");
    cog_verb_register(a1, (intptr_t)cog_returnex, "returnex");
    cog_verb_register(a1, (intptr_t)cog_getparam, "getparam");
    cog_verb_register(a1, (intptr_t)cog_setparam, "setparam");
    cog_verb_register(a1, (intptr_t)cog_enableirmode, "enableirmode");
    cog_verb_register(a1, (intptr_t)cog_disableirmode, "disableirmode");
    cog_verb_register(a1, (intptr_t)cog_setinvflags, "setinvflags");
    cog_verb_register(a1, (intptr_t)cog_setmapmodeflags, "setmapmodeflags");
    cog_verb_register(a1, (intptr_t)cog_getmapmodeflag, "getmapmodeflag");
    cog_verb_register(a1, (intptr_t)cog_clearmapmodeflag, "clearmapmodeflag");
    cog_verb_register(a1, (intptr_t)cog_newcoloreffect, "newcoloreffect");
    cog_verb_register(a1, (intptr_t)cog_freecoloreffect_modifycoloreffect, "freecoloreffect_modifycoloreffect");
    cog_verb_register(a1, (intptr_t)cog_freecoloreffect_modifycoloreffect, "freecoloreffect_modifycoloreffect");
    cog_verb_register(a1, (intptr_t)cog_adddynamicint, "adddynamicint");
    cog_verb_register(a1, (intptr_t)cog_adddynamicadd, "adddynamicadd");
    cog_verb_register(a1, (intptr_t)cog_getmaterialcel, "getmaterialcel");
    cog_verb_register(a1, (intptr_t)cog_setmaterialcel, "setmaterialcel");
    cog_verb_register(a1, (intptr_t)cog_setcamerafocus, "setcamerafocus");
    cog_verb_register(a1, (intptr_t)cog_getprimaryfocus, "getprimaryfocus");
    cog_verb_register(a1, (intptr_t)cog_getsecondaryfocus, "getsecondaryfocus");
    cog_verb_register(a1, (intptr_t)cog_setcurrentcamera, "setcurrentcamera");
    cog_verb_register(a1, (intptr_t)cog_getcurrentcamera, "getcurrentcamera");
    cog_verb_register(a1, (intptr_t)cog_cyclecamera, "cyclecamera");
    cog_verb_register(a1, (intptr_t)cog_setpovshake, "setpovshake");
    cog_verb_register(a1, (intptr_t)cog_setcamerastate, "setcamerastate");
    cog_verb_register(a1, (intptr_t)cog_getcamerastate, "getcamerastate");
    cog_verb_register(a1, (intptr_t)cog_heapnew, "heapnew");
    cog_verb_register(a1, (intptr_t)cog_heapset, "heapset");
    cog_verb_register(a1, (intptr_t)cog_heapget, "heapget");
    cog_verb_register(a1, (intptr_t)cog_heapfree, "heapfree");
    cog_verb_register(a1, (intptr_t)cog_getselfcog, "getselfcog");
    cog_verb_register(a1, (intptr_t)cog_getmastercog, "getmastercog");
    cog_verb_register(a1, (intptr_t)cog_setmastercog, "setmastercog");
    cog_verb_register(a1, (intptr_t)cog_setmultimodeflags, "setmultimodeflags");
    cog_verb_register(a1, (intptr_t)cog_getmultimodeflags, "getmultimodeflags");
    cog_verb_register(a1, (intptr_t)cog_clearmultimodeflags, "clearmultimodeflags");
    cog_verb_register(a1, (intptr_t)cog_ismulti, "ismulti");
    cog_verb_register(a1, (intptr_t)cog_isserver, "isserver");
    cog_verb_register(a1, (intptr_t)cog_setteamscore, "setteamscore");
    cog_verb_register(a1, (intptr_t)cog_getteamscore, "getteamscore");
    cog_verb_register(a1, (intptr_t)cog_settimelimit, "settimelimit");
    cog_verb_register(a1, (intptr_t)cog_gettimelimit, "gettimelimit");
    cog_verb_register(a1, (intptr_t)cog_setscorelimit, "setscorelimit");
    cog_verb_register(a1, (intptr_t)cog_getscorelimit, "getscorelimit");
    cog_verb_register(a1, (intptr_t)cog_sendtrigger, "sendtrigger");
    cog_verb_register(a1, (intptr_t)cog_autosavegame, "autosavegame");
}

void cog_thing_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_waitforstop, "waitforstop");
    cog_verb_register(a1, (intptr_t)cog_stopthing, "stopthing");
    cog_verb_register(a1, (intptr_t)cog_destroything, "destroything");
    cog_verb_register(a1, (intptr_t)cog_getthinghealth_gethealth, "getthinghealth");
    cog_verb_register(a1, (intptr_t)cog_getthinghealth_gethealth, "gethealth");
    cog_verb_register(a1, (intptr_t)cog_healthing, "healthing");
    cog_verb_register(a1, (intptr_t)cog_getthinglight, "getthinglight");
    cog_verb_register(a1, (intptr_t)cog_setthinglight_thinglight, "setthinglight");
    cog_verb_register(a1, (intptr_t)cog_setthinglight_thinglight, "thinglight");
    cog_verb_register(a1, (intptr_t)cog_thinglightanim, "thinglightanim");
    cog_verb_register(a1, (intptr_t)cog_rotate, "rotate");
    cog_verb_register(a1, (intptr_t)cog_creatething, "creatething");
    cog_verb_register(a1, (intptr_t)cog_createthingnr, "createthingnr");
    cog_verb_register(a1, (intptr_t)cog_createthingatp, "createthingatp");
    cog_verb_register(a1, (intptr_t)cog_createthingatposnr, "createthingatposnr");
    cog_verb_register(a1, (intptr_t)cog_rotatepivot, "rotatepivot");
    cog_verb_register(a1, (intptr_t)cog_capturething, "capturething");
    cog_verb_register(a1, (intptr_t)cog_releasething, "releasething");
    cog_verb_register(a1, (intptr_t)cog_setthingvel, "setthingvel");
    cog_verb_register(a1, (intptr_t)cog_addthingvel, "addthingvel");
    cog_verb_register(a1, (intptr_t)cog_applyforce, "applyforce");
    cog_verb_register(a1, (intptr_t)cog_detachthing, "detachthing");
    cog_verb_register(a1, (intptr_t)cog_getattachflags_getthingattachflags, "getattachflags");
    cog_verb_register(a1, (intptr_t)cog_getattachflags_getthingattachflags, "getthingattachflags");
    cog_verb_register(a1, (intptr_t)cog_attachthingtosurf, "attachthingtosurf");
    cog_verb_register(a1, (intptr_t)cog_attachthingtothing, "attachthingtothing");
    cog_verb_register(a1, (intptr_t)cog_setarmedmode, "setarmedmode");
    cog_verb_register(a1, (intptr_t)cog_setthingflags, "setthingflags");
    cog_verb_register(a1, (intptr_t)cog_clearthingflags, "clearthingflags");
    cog_verb_register(a1, (intptr_t)cog_teleportthing, "teleportthing");
    cog_verb_register(a1, (intptr_t)cog_setthingtype, "setthingtype");
    cog_verb_register(a1, (intptr_t)cog_setcollidetype, "setcollidetype");
    cog_verb_register(a1, (intptr_t)cog_setheadlightintensity, "setheadlightintensity");
    cog_verb_register(a1, (intptr_t)cog_getthingmode, "getthingmode");
    cog_verb_register(a1, (intptr_t)cog_setthingmode, "setthingmode");
    cog_verb_register(a1, (intptr_t)cog_getthinglightmode, "getthinglightmode");
    cog_verb_register(a1, (intptr_t)cog_setthinglightmode, "setthinglightmode");
    cog_verb_register(a1, (intptr_t)cog_getthingtexmode, "getthingtexmode");
    cog_verb_register(a1, (intptr_t)cog_setthingtexmode, "setthingtexmode");
    cog_verb_register(a1, (intptr_t)cog_getthingcurgeomode, "getthingcurgeomode");
    cog_verb_register(a1, (intptr_t)cog_setthingcurgeomode, "setthingcurgeomode");
    cog_verb_register(a1, (intptr_t)cog_getthingcurlightmode, "getthingcurlightmode");
    cog_verb_register(a1, (intptr_t)cog_setthingcurlightmode, "setthingcurlightmode");
    cog_verb_register(a1, (intptr_t)cog_getthingcurtexmode, "getthingcurtexmode");
    cog_verb_register(a1, (intptr_t)cog_setthingcurtexmode, "setthingcurtexmode");
    cog_verb_register(a1, (intptr_t)cog_setactorextras, "setactorextras");
    cog_verb_register(a1, (intptr_t)cog_getthingtype, "getthingtype");
    cog_verb_register(a1, (intptr_t)cog_isthingmoving_ismoving, "isthingmoving");
    cog_verb_register(a1, (intptr_t)cog_isthingmoving_ismoving, "ismoving");
    cog_verb_register(a1, (intptr_t)cog_getcurframe, "getcurframe");
    cog_verb_register(a1, (intptr_t)cog_getgoalframe, "getgoalframe");
    cog_verb_register(a1, (intptr_t)cog_getthingparent, "getthingparent");
    cog_verb_register(a1, (intptr_t)cog_getthingsector, "getthingsector");
    cog_verb_register(a1, (intptr_t)cog_getthingpos, "getthingpos");
    cog_verb_register(a1, (intptr_t)cog_setthingpos, "setthingpos");
    cog_verb_register(a1, (intptr_t)cog_getthingvel, "getthingvel");
    cog_verb_register(a1, (intptr_t)cog_getthinguvec, "getthinguvec");
    cog_verb_register(a1, (intptr_t)cog_getthinglvec, "getthinglvec");
    cog_verb_register(a1, (intptr_t)cog_getthingrvec, "getthingrvec");
    cog_verb_register(a1, (intptr_t)cog_getthingflags, "getthingflags");
    cog_verb_register(a1, (intptr_t)cog_getcollidetype, "getcollidetype");
    cog_verb_register(a1, (intptr_t)cog_getheadlightin, "getheadlightin");
    cog_verb_register(a1, (intptr_t)cog_isthingvisible, "isthingvisible");
    cog_verb_register(a1, (intptr_t)cog_setthingpulse, "setthingpulse");
    cog_verb_register(a1, (intptr_t)cog_setthingtimer, "setthingtimer");
    cog_verb_register(a1, (intptr_t)cog_getinv, "getinv");
    cog_verb_register(a1, (intptr_t)cog_setinv, "setinv");
    cog_verb_register(a1, (intptr_t)cog_changeinv, "changeinv");
    cog_verb_register(a1, (intptr_t)cog_getinvcog, "getinvcog");
    cog_verb_register(a1, (intptr_t)cog_getinvmin, "getinvmin");
    cog_verb_register(a1, (intptr_t)cog_getinvmax, "getinvmax");
    cog_verb_register(a1, (intptr_t)cog_getcurinvweapon, "getcurinvweapon");
    cog_verb_register(a1, (intptr_t)cog_setcurinvweapon, "setcurinvweapon");
    cog_verb_register(a1, (intptr_t)cog_playkey, "playkey");
    cog_verb_register(a1, (intptr_t)cog_stopkey, "stopkey");
    cog_verb_register(a1, (intptr_t)cog_setthingmodel, "setthingmodel");
    cog_verb_register(a1, (intptr_t)cog_getthingmodel, "getthingmodel");
    cog_verb_register(a1, (intptr_t)cog_playmode, "playmode");
    cog_verb_register(a1, (intptr_t)cog_getmajormode, "getmajormode");
    cog_verb_register(a1, (intptr_t)cog_firstthinginsector, "firstthinginsector");
    cog_verb_register(a1, (intptr_t)cog_nextthinginsector, "nextthinginsector");
    cog_verb_register(a1, (intptr_t)cog_prevthinginseector, "prevthinginseector");
    cog_verb_register(a1, (intptr_t)cog_movetoframe, "movetoframe");
    cog_verb_register(a1, (intptr_t)cog_skiptoframe, "skiptoframe");
    cog_verb_register(a1, (intptr_t)cog_jumptoframe, "jumptoframe");
    cog_verb_register(a1, (intptr_t)cog_pathmovepause, "pathmovepause");
    cog_verb_register(a1, (intptr_t)cog_pathmoveresume, "pathmoveresume");
    cog_verb_register(a1, (intptr_t)cog_getthingtemplate, "getthingtemplate");
    cog_verb_register(a1, (intptr_t)cog_damagething, "damagething");
    cog_verb_register(a1, (intptr_t)cog_setlifeleft, "setlifeleft");
    cog_verb_register(a1, (intptr_t)cog_getlifeleft, "getlifeleft");
    cog_verb_register(a1, (intptr_t)cog_setthingthrust, "setthingthrust");
    cog_verb_register(a1, (intptr_t)cog_getthingthrust, "getthingthrust");
    cog_verb_register(a1, (intptr_t)cog_setthinghealth_sethealth, "setthinghealth");
    cog_verb_register(a1, (intptr_t)cog_setthinghealth_sethealth, "sethealth");
    cog_verb_register(a1, (intptr_t)cog_amputatejoint, "amputatejoint");
    cog_verb_register(a1, (intptr_t)cog_setactorweapon, "setactorweapon");
    cog_verb_register(a1, (intptr_t)cog_getactorweapon, "getactorweapon");
    cog_verb_register(a1, (intptr_t)cog_getphysicsflag, "getphysicsflag");
    cog_verb_register(a1, (intptr_t)cog_setphysicsflag, "setphysicsflag");
    cog_verb_register(a1, (intptr_t)cog_clearphysicsflag, "clearphysicsflag");
    cog_verb_register(a1, (intptr_t)cog_skilltarget, "skilltarget");
    cog_verb_register(a1, (intptr_t)cog_parsearg, "parsearg");
    cog_verb_register(a1, (intptr_t)cog_getthingrotvel, "getthingrotvel");
    cog_verb_register(a1, (intptr_t)cog_setthingrotvel, "setthingrotvel");
    cog_verb_register(a1, (intptr_t)cog_getthinglook, "getthinglook");
    cog_verb_register(a1, (intptr_t)cog_isthingcrouching_iscrouching, "isthingcrouching");
    cog_verb_register(a1, (intptr_t)cog_isthingcrouching_iscrouching, "iscrouching");
    cog_verb_register(a1, (intptr_t)cog_getthingclasscog, "getthingclasscog");
    cog_verb_register(a1, (intptr_t)cog_setthingclasscog, "setthingclasscog");
    cog_verb_register(a1, (intptr_t)cog_getthingcapturecog, "getthingcapturecog");
    cog_verb_register(a1, (intptr_t)cog_setthingcapturecog, "setthingcapturecog");
    cog_verb_register(a1, (intptr_t)cog_getthingrespawn, "getthingrespawn");
    cog_verb_register(a1, (intptr_t)cog_getthingsignature, "getthingsignature");
    cog_verb_register(a1, (intptr_t)cog_setthingattachflags, "setthingattachflags");
    cog_verb_register(a1, (intptr_t)cog_clearthingattachflags, "clearthingattachflags");
    cog_verb_register(a1, (intptr_t)cog_getparticlesize, "getparticlesize");
    cog_verb_register(a1, (intptr_t)cog_setparticlesize, "setparticlesize");
    cog_verb_register(a1, (intptr_t)cog_getparticlegrowthspeed, "getparticlegrowthspeed");
    cog_verb_register(a1, (intptr_t)cog_setparticlegrowthspeed, "setparticlegrowthspeed");
    cog_verb_register(a1, (intptr_t)cog_getparticletimeoutrate, "getparticletimeoutrate");
    cog_verb_register(a1, (intptr_t)cog_setparticletimeoutrate, "setparticletimeoutrate");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_getXflags, "getXflags");
    cog_verb_register(a1, (intptr_t)cog_setXflags, "setXflags");
    cog_verb_register(a1, (intptr_t)cog_clearXflags, "clearXflags");
    cog_verb_register(a1, (intptr_t)cog_takeitem, "takeitem");
    cog_verb_register(a1, (intptr_t)cog_haslos, "haslos");
    cog_verb_register(a1, (intptr_t)cog_getthingfireoffset, "getthingfireoffset");
    cog_verb_register(a1, (intptr_t)cog_setthingfireoffset, "setthingfireoffset");
    cog_verb_register(a1, (intptr_t)cog_getthinguserdata, "getthinguserdata");
    cog_verb_register(a1, (intptr_t)cog_setthinguserdata, "setthinguserdata");
    cog_verb_register(a1, (intptr_t)cog_getthingcollidesize, "getthingcollidesize");
    cog_verb_register(a1, (intptr_t)cog_setthingcollidesize, "setthingcollidesize");
    cog_verb_register(a1, (intptr_t)cog_getthingmovesize, "getthingmovesize");
    cog_verb_register(a1, (intptr_t)cog_setthingmovesize, "setthingmovesize");
    cog_verb_register(a1, (intptr_t)cog_getthingmass, "getthingmass");
    cog_verb_register(a1, (intptr_t)cog_setthingmass, "setthingmass");
    cog_verb_register(a1, (intptr_t)cog_syncthingpos, "syncthingpos");
    cog_verb_register(a1, (intptr_t)cog_syncthingattachment, "syncthingattachment");
    cog_verb_register(a1, (intptr_t)cog_syncthingstate, "syncthingstate");
    cog_verb_register(a1, (intptr_t)cog_attachthingtothingex, "attachthingtothingex");
}

void cog_ai_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_aigetmode, "aigetmode");
    cog_verb_register(a1, (intptr_t)cog_aisetmode, "aisetmode");
    cog_verb_register(a1, (intptr_t)cog_aiclearmode, "aiclearmode");
    cog_verb_register(a1, (intptr_t)cog_aigetmovepos, "aigetmovepos");
    cog_verb_register(a1, (intptr_t)cog_aisetmovepos, "aisetmovepos");
    cog_verb_register(a1, (intptr_t)cog_firstthinginview, "firstthinginview");
    cog_verb_register(a1, (intptr_t)cog_nextthinginview, "nextthinginview");
    cog_verb_register(a1, (intptr_t)cog_thingviewdot, "thingviewdot");
    cog_verb_register(a1, (intptr_t)cog_aisetfiretarget, "aisetfiretarget");
    cog_verb_register(a1, (intptr_t)cog_aisetmovething, "aisetmovething");
    cog_verb_register(a1, (intptr_t)cog_aisetlookpos, "aisetlookpos");
    cog_verb_register(a1, (intptr_t)cog_aisetmovespeed, "aisetmovespeed");
    cog_verb_register(a1, (intptr_t)cog_aisetlookframe, "aisetlookframe");
    cog_verb_register(a1, (intptr_t)cog_aisetmoveframe, "aisetmoveframe");
    cog_verb_register(a1, (intptr_t)cog_isaitargetinsight, "isaitargetinsight");
    cog_verb_register(a1, (intptr_t)cog_aiflee, "aiflee");
    cog_verb_register(a1, (intptr_t)cog_aisetclass, "aisetclass");
    cog_verb_register(a1, (intptr_t)cog_aijump, "aijump");
}

void cog_surface_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_getsurfaceadjoin, "getsurfaceadjoin");
    cog_verb_register(a1, (intptr_t)cog_getserfacesector, "getserfacesector");
    cog_verb_register(a1, (intptr_t)cog_getnusurfacevertices, "getnusurfacevertices");
    cog_verb_register(a1, (intptr_t)cog_getsurfacevertexpos, "getsurfacevertexpos");
    cog_verb_register(a1, (intptr_t)cog_sethorizonskyoffset, "sethorizonskyoffset");
    cog_verb_register(a1, (intptr_t)cog_gethorizonskyoffset, "gethorizonskyoffset");
    cog_verb_register(a1, (intptr_t)cog_setceilingskyoffset, "setceilingskyoffset");
    cog_verb_register(a1, (intptr_t)cog_getceilingskyoffset, "getceilingskyoffset");
    cog_verb_register(a1, (intptr_t)cog_slidehorizonsky, "slidehorizonsky");
    cog_verb_register(a1, (intptr_t)cog_slideceilingsky, "slideceilingsky");
    cog_verb_register(a1, (intptr_t)cog_getsurfacecount, "getsurfacecount");
    cog_verb_register(a1, (intptr_t)cog_slidewall_slidesurface, "slidewall");
    cog_verb_register(a1, (intptr_t)cog_slidewall_slidesurface, "slidesurface");
    cog_verb_register(a1, (intptr_t)cog_getwallcel, "getwallcel");
    cog_verb_register(a1, (intptr_t)cog_setwallcel, "setwallcel");
    cog_verb_register(a1, (intptr_t)cog_getwallcel, "getwallcel");
    cog_verb_register(a1, (intptr_t)cog_setwallcel, "setwallcel");
    cog_verb_register(a1, (intptr_t)cog_getsurfacemat, "getsurfacemat");
    cog_verb_register(a1, (intptr_t)cog_setsurfacemat, "setsurfacemat");
    cog_verb_register(a1, (intptr_t)cog_getsurfaceflag, "getsurfaceflag");
    cog_verb_register(a1, (intptr_t)cog_setsurfaceflag, "setsurfaceflag");
    cog_verb_register(a1, (intptr_t)cog_clearsurfaceflag, "clearsurfaceflag");
    cog_verb_register(a1, (intptr_t)cog_getajoinflags, "getajoinflags");
    cog_verb_register(a1, (intptr_t)cog_setadjoinflags, "setadjoinflags");
    cog_verb_register(a1, (intptr_t)cog_clearadjoinflags, "clearadjoinflags");
    cog_verb_register(a1, (intptr_t)cog_setfacetype, "setfacetype");
    cog_verb_register(a1, (intptr_t)cog_clearfacetype, "clearfacetype");
    cog_verb_register(a1, (intptr_t)cog_getfacetype, "getfacetype");
    cog_verb_register(a1, (intptr_t)cog_setfacegeomode, "setfacegeomode");
    cog_verb_register(a1, (intptr_t)cog_getfacegeomode, "getfacegeomode");
    cog_verb_register(a1, (intptr_t)cog_setfacelightmode, "setfacelightmode");
    cog_verb_register(a1, (intptr_t)cog_getfacelightmode, "getfacelightmode");
    cog_verb_register(a1, (intptr_t)cog_setfacetexmode, "setfacetexmode");
    cog_verb_register(a1, (intptr_t)cog_getfacetexmode, "getfacetexmode");
    cog_verb_register(a1, (intptr_t)cog_getsurfacelight, "getsurfacelight");
    cog_verb_register(a1, (intptr_t)cog_setsurfacelight, "setsurfacelight");
    cog_verb_register(a1, (intptr_t)cog_setsurfacelight, "setsurfacelight");
    cog_verb_register(a1, (intptr_t)cog_getsurfacecenter, "getsurfacecenter");
    cog_verb_register(a1, (intptr_t)cog_getsurfacecenter, "getsurfacecenter");
    cog_verb_register(a1, (intptr_t)cog_surfacelightanim, "surfacelightanim");
    cog_verb_register(a1, (intptr_t)cog_getsurfacenormal, "getsurfacenormal");
    cog_verb_register(a1, (intptr_t)cog_syncsurface, "syncsurface");

}

void cog_noise_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_playsong, "playsong");
    cog_verb_register(a1, (intptr_t)cog_playsoundthing, "playsoundthing");
    cog_verb_register(a1, (intptr_t)cog_playsoundpos, "playsoundpos");
    cog_verb_register(a1, (intptr_t)cog_playsoundlocal, "playsoundlocal");
    cog_verb_register(a1, (intptr_t)cog_playsoundglobal, "playsoundglobal");
    cog_verb_register(a1, (intptr_t)cog_stopsound, "stopsound");
    cog_verb_register(a1, (intptr_t)cog_loadsound, "loadsound");
    cog_verb_register(a1, (intptr_t)cog_playsoundclass, "playsoundclass");
    cog_verb_register(a1, (intptr_t)cog_changesoundvol, "changesoundvol");
    cog_verb_register(a1, (intptr_t)cog_changesoundpitch, "changesoundpitch");
    cog_verb_register(a1, (intptr_t)cog_sectorsound, "sectorsound");
    cog_verb_register(a1, (intptr_t)cog_setmusicvol, "setmusicvol");
    cog_verb_register(a1, (intptr_t)cog_getsoundlen, "getsoundlen");

}

void cog_sector_verbs_init(void* a1)
{
    cog_verb_register(a1, (intptr_t)cog_getsectorint, "getsectorint");
    cog_verb_register(a1, (intptr_t)cog_setsectorint, "setsectorint");
    cog_verb_register(a1, (intptr_t)cog_setsectoradjoins_sectoradjoins, "setsectoradjoins");
    cog_verb_register(a1, (intptr_t)cog_setsectoradjoins_sectoradjoins, "sectoradjoins");
    cog_verb_register(a1, (intptr_t)cog_getsectorlight, "getsectorlight");
    cog_verb_register(a1, (intptr_t)cog_setsectorlight_sectorlight, "setsectorlight");
    cog_verb_register(a1, (intptr_t)cog_setsectorlight_sectorlight, "sectorlight");
    cog_verb_register(a1, (intptr_t)cog_getcolormap, "getcolormap");
    cog_verb_register(a1, (intptr_t)cog_getcolormap, "getcolormap");
    cog_verb_register(a1, (intptr_t)cog_setcolormap, "setcolormap");
    cog_verb_register(a1, (intptr_t)cog_setcolormap, "setcolormap");
    cog_verb_register(a1, (intptr_t)cog_getsectorthrust, "getsectorthrust");
    cog_verb_register(a1, (intptr_t)cog_setsectorthrust, "setsectorthrust");
    cog_verb_register(a1, (intptr_t)cog_setsectorthrust, "setsectorthrust");
    cog_verb_register(a1, (intptr_t)cog_getsectorflags, "getsectorflags");
    cog_verb_register(a1, (intptr_t)cog_setsectorflags, "setsectorflags");
    cog_verb_register(a1, (intptr_t)cog_clearsectorflags, "clearsectorflags");
    cog_verb_register(a1, (intptr_t)cog_getsectorthingcount, "getsectorthingcount");
    cog_verb_register(a1, (intptr_t)cog_getsectorthingcount, "getsectorthingcount");
    cog_verb_register(a1, (intptr_t)cog_getsectorplayercount, "getsectorplayercount");
    cog_verb_register(a1, (intptr_t)cog_getsectorplayercount, "getsectorplayercount");
    cog_verb_register(a1, (intptr_t)cog_getsectorcount, "getsectorcount");
    cog_verb_register(a1, (intptr_t)cog_getsectorcenter, "getsectorcenter");
    cog_verb_register(a1, (intptr_t)cog_getsectornumvertices, "getsectornumvertices");
    cog_verb_register(a1, (intptr_t)cog_getsectorvertexpos, "getsectorvertexpos");
    cog_verb_register(a1, (intptr_t)cog_getnumsectorsurfaces, "getnumsectorsurfaces");
    cog_verb_register(a1, (intptr_t)cog_getsectorsurfaceref, "getsectorsurfaceref");
    cog_verb_register(a1, (intptr_t)cog_syncsector, "syncsector");
}

void cog_player_verbs_init(void* a1)
{
  cog_verb_register(a1, (intptr_t)cog_setinvactivate, "setinvactivate");
  cog_verb_register(a1, (intptr_t)cog_setinvavailable, "setinvavailable");
  cog_verb_register(a1, (intptr_t)cog_isinvactivated, "isinvactivated");
  cog_verb_register(a1, (intptr_t)cog_isinvavailable, "isinvavailable");
  cog_verb_register(a1, (intptr_t)cog_setgoalflags, "setgoalflags");
  cog_verb_register(a1, (intptr_t)cog_cleargoalflags, "cleargoalflags");
  cog_verb_register(a1, (intptr_t)cog_getnumplayers, "getnumplayers");
  cog_verb_register(a1, (intptr_t)cog_getmaxplayers, "getmaxplayers");
  cog_verb_register(a1, (intptr_t)cog_getabsolutemax, "getabsolutemax");
  cog_verb_register(a1, (intptr_t)cog_getlocalplayer, "getlocalplayer");
  cog_verb_register(a1, (intptr_t)cog_getplayerthing, "getplayerthing");
  cog_verb_register(a1, (intptr_t)cog_getplayernum, "getplayernum");
  cog_verb_register(a1, (intptr_t)cog_getplayerteam, "getplayerteam");
  cog_verb_register(a1, (intptr_t)cog_setplayerteam, "setplayerteam");
  cog_verb_register(a1, (intptr_t)cog_getplayerscore, "getplayerscore");
  cog_verb_register(a1, (intptr_t)cog_setplayerscore, "setplayerscore");
  cog_verb_register(a1, (intptr_t)cog_getplayerkills, "getplayerkills");
  cog_verb_register(a1, (intptr_t)cog_setplayerkills, "setplayerkills");
  cog_verb_register(a1, (intptr_t)cog_getplayerkilled, "getplayerkilled");
  cog_verb_register(a1, (intptr_t)cog_setplayerkilled, "setplayerkilled");
  cog_verb_register(a1, (intptr_t)cog_getplayersuicide, "getplayersuicide");
  cog_verb_register(a1, (intptr_t)cog_setplayersuicide, "setplayersuicide");
  cog_verb_register(a1, (intptr_t)cog_pickupbackpack, "pickupbackpack");
  cog_verb_register(a1, (intptr_t)cog_createbackpack, "createbackpack");
  cog_verb_register(a1, (intptr_t)cog_nthbackpackbin, "nthbackpackbin");
  cog_verb_register(a1, (intptr_t)cog_nthbackpackvalue, "nthbackpackvalue");
  cog_verb_register(a1, (intptr_t)cog_numbackpackitems, "numbackpackitems");
  cog_verb_register(a1, (intptr_t)cog_getautoswitch, "getautoswitch");
  cog_verb_register(a1, (intptr_t)cog_setautoswitch, "setautoswitch");
  cog_verb_register(a1, (intptr_t)cog_getautopickup, "getautopickup");
  cog_verb_register(a1, (intptr_t)cog_setautopickup, "setautopickup");
  cog_verb_register(a1, (intptr_t)cog_getautoreload, "getautoreload");
  cog_verb_register(a1, (intptr_t)cog_setautoreload, "setautoreload");
  cog_verb_register(a1, (intptr_t)cog_getrespawnmask, "getrespawnmask");
  cog_verb_register(a1, (intptr_t)cog_setrespawnmask, "setrespawnmask");
  cog_verb_register(a1, (intptr_t)cog_activatebin, "activatebin");
  cog_verb_register(a1, (intptr_t)cog_deactivatebin, "deactivatebin");
  cog_verb_register(a1, (intptr_t)cog_setbinwait, "setbinwait");
  cog_verb_register(a1, (intptr_t)cog_getnumplayersinteam, "getnumplayersinteam");
  cog_verb_register(a1, (intptr_t)cog_addscoretoteam, "addscoretoteam");
  cog_verb_register(a1, (intptr_t)cog_syncscores, "syncscores");
}

int cog_init()
{
    struct hashmap_entry *v3; // eax
    hashmap_entry *v4; // eax
    hashmap_entry *v5; // eax
    hashmap_entry *v6; // eax
    hashmap_entry *v7; // eax
    struct cog_entry a2; // [esp+8h] [ebp-10h]

    g_cog_symboltable_hashmap = cog_alloc_symboltable(512);
    if (!g_cog_symboltable_hashmap )
    {
        jk_assert(common_functions_ptr_2->print_loglevel0, ".\Cog\sithCog.c", 118, "Could not allocate COG symboltable.");
        return 0;
    }
  
    g_cog_hashtable = hashmap_init_maybe(256);
    if (!g_cog_hashtable)
    {
        jk_assert(common_functions_ptr_2->print_loglevel0, ".\Cog\sithCog.c", 124, "Could not allocate COG hashtable.");
        return 0;
    }
    *(uint32_t*)(g_cog_symboltable_hashmap + 16) = 256;
    cog_math_verbs_init(g_cog_symboltable_hashmap);
    cog_thing_verbs_init(g_cog_symboltable_hashmap);
    cog_ai_verbs_init(g_cog_symboltable_hashmap);
    cog_surface_verbs_init(g_cog_symboltable_hashmap);
    cog_noise_verbs_init(g_cog_symboltable_hashmap);
    cog_sector_verbs_init(g_cog_symboltable_hashmap);
    cog_player_verbs_init(g_cog_symboltable_hashmap);
    v3 = hashmap_create_entry(g_cog_symboltable_hashmap, "activate");
    if ( v3 )
    {
        a2.type = COG_TYPE_MESSAGE;
        a2.val = 1;
        hashmap_set_entry(v3, &a2);
    }
    v4 = hashmap_create_entry(g_cog_symboltable_hashmap, "activated");
    if ( v4 )
    {
        a2.type = COG_TYPE_MESSAGE;
        a2.val = 1;
        hashmap_set_entry(v4, &a2);
    }
    v5 = hashmap_create_entry(g_cog_symboltable_hashmap, "startup");
    if ( v5 )
    {
        a2.type = COG_TYPE_MESSAGE;
        a2.val = COG_TYPE_MESSAGE;
        hashmap_set_entry(v5, &a2);
    }
    v6 = hashmap_create_entry(g_cog_symboltable_hashmap, "timer");
    if ( v6 )
    {
        a2.type = COG_TYPE_MESSAGE;
        a2.val = 4;
        hashmap_set_entry(v6, &a2);
    }
    v7 = hashmap_create_entry(g_cog_symboltable_hashmap, "blocked");
    if ( v7 )
    {
        a2.type = COG_TYPE_MESSAGE;
        a2.val = 5;
        hashmap_set_entry(v7, &a2);
    }
    cog_register_message(g_cog_symboltable_hashmap, 6, "entered");
    cog_register_message(g_cog_symboltable_hashmap, 7, "exited");
    cog_register_message(g_cog_symboltable_hashmap, 8, "crossed");
    cog_register_message(g_cog_symboltable_hashmap, 9, "sighted");
    cog_register_message(g_cog_symboltable_hashmap, 10, "damaged");
    cog_register_message(g_cog_symboltable_hashmap, 11, "arrived");
    cog_register_message(g_cog_symboltable_hashmap, 12, "killed");
    cog_register_message(g_cog_symboltable_hashmap, 13, "pulse");
    cog_register_message(g_cog_symboltable_hashmap, 14, "touched");
    cog_register_message(g_cog_symboltable_hashmap, 15, "created");
    cog_register_message(g_cog_symboltable_hashmap, 16, "loading");
    cog_register_message(g_cog_symboltable_hashmap, 17, "selected");
    cog_register_message(g_cog_symboltable_hashmap, 18, "deselected");
    cog_register_message(g_cog_symboltable_hashmap, 20, "changed");
    cog_register_message(g_cog_symboltable_hashmap, 21, "deactivated");
    cog_register_message(g_cog_symboltable_hashmap, 22, "shutdown");
    cog_register_message(g_cog_symboltable_hashmap, 23, "respawn");
    cog_register_message(g_cog_symboltable_hashmap, 2, "removed");
    cog_register_message(g_cog_symboltable_hashmap, 19, "autoselect");
    cog_register_message(g_cog_symboltable_hashmap, 24, "aievent");
    cog_register_message(g_cog_symboltable_hashmap, 25, "skill");
    cog_register_message(g_cog_symboltable_hashmap, 26, "taken");
    cog_register_message(g_cog_symboltable_hashmap, 27, "user0");
    cog_register_message(g_cog_symboltable_hashmap, 28, "user1");
    cog_register_message(g_cog_symboltable_hashmap, 29, "user2");
    cog_register_message(g_cog_symboltable_hashmap, 30, "user3");
    cog_register_message(g_cog_symboltable_hashmap, 31, "user4");
    cog_register_message(g_cog_symboltable_hashmap, 32, "user5");
    cog_register_message(g_cog_symboltable_hashmap, 33, "user6");
    cog_register_message(g_cog_symboltable_hashmap, 34, "user7");
    cog_register_message(g_cog_symboltable_hashmap, 35, "newplayer");
    cog_register_message(g_cog_symboltable_hashmap, 36, "fire");
    cog_register_message(g_cog_symboltable_hashmap, 37, "join");
    cog_register_message(g_cog_symboltable_hashmap, 38, "leave");
    cog_register_message(g_cog_symboltable_hashmap, 39, "splash");
    cog_register_message(g_cog_symboltable_hashmap, 40, "trigger");
    cog_register_global_message(g_cog_symboltable_hashmap, "global0", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global1", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global2", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global3", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global4", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global5", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global6", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global7", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global8", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global9", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global10", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global11", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global12", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global13", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global14", 0);
    cog_register_global_message(g_cog_symboltable_hashmap, "global15", 0);
    cog_register_msg_hander(4, (int)sub_4E0640, 0, 2);
    //cog_initialized = 1;
    return 1;
}
