/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define FLEX_SCANNER

#include "globals.h"

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
//#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
 #if !defined(_MSC_VER)
char *malloc();
int free();
int read();
#endif // !defined(_MSC_VER)
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) _fwrite( (char *) yytext, yyleng, 1, (FILE*)yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = pSithHS->fileRead((stdFile_t)yyin, (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) _fputs( msg, stderr ); \
		(void) _fputs( "\n", stderr ); \
		/*(void) putc( '\n', stderr );*/ \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, (FILE*)yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "cog.l"
#define INITIAL 0
# line 7 "cog.l"
#include <stdio.h>
#include "Cog/sithCogParse.h"
#include "jk.h"
#include "y.tab.h"

#define printf(...) _printf(__VA_ARGS__)
#define fwrite(x,y,z,w) _fwrite(x,y,z,w)
#define atoi(x) _atoi(x)
#define exit(x) jk_exit(x)
#define malloc(x) _malloc(x)
#define free(x) _free(x)
#define memcpy(x,y,z) _memcpy(x,y,z)
#define strlen(x) _strlen(x)
#define strcpy(x,y) _strcpy(x,y)

# line 24 "cog.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
//extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;
//extern stdFile_t yyin, yyout;

//FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
//#define yyin (*(int*)0x00855D90)
//#define yyout (*(int*)0x00855D94)

#define YY_END_OF_BUFFER 57
typedef int yy_state_type;
static const short int yy_accept[121] =
    {   0,
        0,    0,   57,   55,   54,   53,   53,   40,   55,   46,
       48,   39,   55,   34,   35,   44,   43,   31,   42,   38,
       47,   16,   16,   32,   28,   49,   33,   50,   36,   37,
       51,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   29,   52,   30,   41,   27,    0,   20,    0,
       46,   22,    0,   21,    0,   18,   45,   19,   15,    0,
        0,   16,   24,   26,   25,   13,   13,   13,   13,    3,
       13,   13,   13,   13,    7,   13,   13,   13,   23,    0,
       45,   18,    0,    0,   17,   14,   13,   13,   13,   13,
       11,    5,   13,   13,   13,   13,    0,   18,    0,    0,

       19,   13,   12,   13,    4,    6,   13,    8,   13,    0,
       18,    1,   13,   13,   10,   13,    9,   13,    2,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   30,   40,   41,   30,   42,   43,   44,
       30,   45,   46,   47,   48,   30,   49,   50,   30,   30,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   30,   40,   41,   30,   42,
       43,   44,   30,   45,   46,   47,   48,   30,   49,   50,
       30,   30,   51,   52,   53,   54,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static const short int yy_base[126] =
    {   0,
        0,    0,  197,  198,  198,  198,  198,  172,   49,    0,
      198,  186,   46,  198,  198,  198,  198,  198,  198,   38,
      176,   42,   46,  198,  198,  169,  168,  167,  198,  198,
      198,    0,  145,   29,  146,   26,  145,  144,  150,  150,
      137,  145,  198,  130,  198,  198,  198,   58,  198,  178,
        0,  198,   59,  198,  177,   55,    0,   59,   63,   77,
       68,   88,  198,  198,  198,    0,  144,  137,  135,    0,
      130,  141,  129,  126,    0,  125,  128,  131,  198,   95,
        0,   93,  102,   51,  100,  105,  138,  127,  120,  131,
        0,    0,  122,  116,  119,  120,  107,  110,  128,  112,

      114,  115,    0,  104,    0,    0,   90,    0,   82,  126,
      130,    0,   68,   64,    0,   47,    0,   54,    0,  198,
      150,  153,  156,   81,  159
    } ;

static const short int yy_def[126] =
    {   0,
      120,    1,  120,  120,  120,  120,  120,  120,  121,  122,
      120,  120,  123,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  120,  120,  120,  120,  120,  121,  120,  121,
      122,  120,  123,  120,  123,  120,  125,  120,  120,  120,
      120,  120,  120,  120,  120,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  120,  120,
      125,  120,  120,  120,  120,  120,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  120,  120,  120,  120,

      120,  124,  124,  124,  124,  124,  124,  124,  124,  120,
      120,  124,  124,  124,  124,  124,  124,  124,  124,    0,
      120,  120,  120,  120,  120
    } ;

static const short int yy_nxt[253] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,    4,   30,   31,   32,
       32,   33,   34,   35,   36,   37,   38,   32,   39,   32,
       32,   32,   32,   32,   40,   41,   32,   32,   42,   32,
       43,   44,   45,   46,   49,   54,   56,   56,   58,   68,
       59,   59,   58,   49,   62,   62,   71,   72,   54,   85,
       85,   69,   55,   56,   56,   50,   60,   82,   82,   58,
       60,   59,   59,   66,   50,   55,   86,   86,  119,   80,
       84,   61,   84,   83,  118,   85,   85,   60,   86,   86,

       86,   86,   86,   86,   58,  117,   62,   62,   97,  116,
       97,   82,   82,   98,   98,  100,  115,  100,   85,   85,
      101,  101,   60,   86,   86,   98,   98,   99,   98,   98,
      101,  101,  101,  101,  114,   86,   86,   86,   86,   86,
       86,  110,  113,  110,  111,  111,  111,  111,  111,  111,
       48,   48,   48,   51,  112,   51,   53,   53,   53,   81,
      109,   81,  108,  107,  106,  105,  104,  103,  102,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,  120,
      120,   79,   78,   77,   76,   75,   74,   73,   70,   67,
       65,   64,   63,   57,   52,   47,  120,    3,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

static const short int yy_chk[253] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   13,   20,   20,   22,   34,
       22,   22,   23,   48,   23,   23,   36,   36,   53,   84,
       84,   34,   13,   56,   56,    9,   22,   58,   58,   59,
       23,   59,   59,  124,   48,   53,   61,   61,  118,   56,
       60,   22,   60,   58,  116,   60,   60,   59,   61,   61,

       61,   61,   61,   61,   62,  114,   62,   62,   80,  113,
       80,   82,   82,   80,   80,   83,  109,   83,   85,   85,
       83,   83,   62,   86,   86,   97,   97,   82,   98,   98,
      100,  100,  101,  101,  107,   86,   86,   86,   86,   86,
       86,   99,  104,   99,  110,  110,   99,   99,  111,  111,
      121,  121,  121,  122,  102,  122,  123,  123,  123,  125,
       96,  125,   95,   94,   93,   90,   89,   88,   87,   78,
       77,   76,   74,   73,   72,   71,   69,   68,   67,   55,
       50,   44,   42,   41,   40,   39,   38,   37,   35,   33,
       28,   27,   26,   21,   12,    8,    3,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static void idk_stack_scrub()
{
    int scrub[128];
    _memset(scrub, 0, sizeof(scrub));
}

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    /*register*/ yy_state_type yy_current_state;
    /*register*/ YY_CHAR *yy_cp, *yy_bp;
    /*register*/ int yy_act;




    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = (stdFile_t)stdin;

	if ( ! yyout )
	    yyout = (stdFile_t)stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, (FILE*)yyin );
	else
	    yy_current_buffer = yy_create_buffer( (FILE*)yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;
	idk_stack_scrub(); // aaaaaaa where is the undefined data coming from

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    /*register*/ YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 121 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 120 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 26 "cog.l"
{ return(BREAK); }
	YY_BREAK
case 2:
# line 27 "cog.l"
{ return(CONTINUE); }
	YY_BREAK
case 3:
# line 28 "cog.l"
{ return(DO); }
	YY_BREAK
case 4:
# line 29 "cog.l"
{ return(ELSE); }
	YY_BREAK
case 5:
# line 30 "cog.l"
{ return(FOR); }
	YY_BREAK
case 6:
# line 31 "cog.l"
{ return(GOTO); }
	YY_BREAK
case 7:
# line 32 "cog.l"
{ return(IF); }
	YY_BREAK
case 8:
# line 33 "cog.l"
{ return(RETURN); }
	YY_BREAK
case 9:
# line 34 "cog.l"
{ return(RETURN); }
	YY_BREAK
case 10:
# line 35 "cog.l"
{ return(WHILE); }
	YY_BREAK
case 11:
# line 36 "cog.l"
{ yyterminate(); }
	YY_BREAK
case 12:
# line 37 "cog.l"
{ return(CALL); }
	YY_BREAK
case 13:
# line 39 "cog.l"
{ sithCogParse_LexGetSym(yytext); return(IDENTIFIER); }
	YY_BREAK
case 14:
# line 41 "cog.l"
{ _sscanf(yytext, "%x", &yylval.as_int); return(CONSTANT_INT); }
	YY_BREAK
case 15:
# line 42 "cog.l"
{ _sscanf(yytext, "%i", &yylval.as_int); return(CONSTANT_INT); }
	YY_BREAK
case 16:
# line 43 "cog.l"
{ yylval.as_int = _atoi(yytext); return(CONSTANT_INT); }
	YY_BREAK
case 17:
# line 46 "cog.l"
{ yylval.as_float = _atof(yytext); return(CONSTANT_FLOAT); }
	YY_BREAK
case 18:
# line 47 "cog.l"
{ yylval.as_float = _atof(yytext); return(CONSTANT_FLOAT); }
	YY_BREAK
case 19:
# line 48 "cog.l"
{ yylval.as_float = _atof(yytext); return(CONSTANT_FLOAT); }
	YY_BREAK
case 20:
# line 50 "cog.l"
{ sithCogParse_LexAddSymbol(yytext); return(STRING_LITERAL); }
	YY_BREAK
case 21:
# line 51 "cog.l"
{ sithCogParse_LexScanVector3(yytext); return(VECTOR_LITERAL); }
	YY_BREAK
case 22:
# line 53 "cog.l"
{ return(AND_OP); }
	YY_BREAK
case 23:
# line 54 "cog.l"
{ return(OR_OP); }
	YY_BREAK
case 24:
# line 55 "cog.l"
{ return(LE_OP); }
	YY_BREAK
case 25:
# line 56 "cog.l"
{ return(GE_OP); }
	YY_BREAK
case 26:
# line 57 "cog.l"
{ return(EQ_OP); }
	YY_BREAK
case 27:
# line 58 "cog.l"
{ return(NE_OP); }
	YY_BREAK
case 28:
# line 59 "cog.l"
{ return(';'); }
	YY_BREAK
case 29:
# line 60 "cog.l"
{ return('{'); }
	YY_BREAK
case 30:
# line 61 "cog.l"
{ return('}'); }
	YY_BREAK
case 31:
# line 62 "cog.l"
{ return(','); }
	YY_BREAK
case 32:
# line 63 "cog.l"
{ return(':'); }
	YY_BREAK
case 33:
# line 64 "cog.l"
{ return('='); }
	YY_BREAK
case 34:
# line 65 "cog.l"
{ return('('); }
	YY_BREAK
case 35:
# line 66 "cog.l"
{ return(')'); }
	YY_BREAK
case 36:
# line 67 "cog.l"
{ return('['); }
	YY_BREAK
case 37:
# line 68 "cog.l"
{ return(']'); }
	YY_BREAK
case 38:
# line 69 "cog.l"
{ return('.'); }
	YY_BREAK
case 39:
# line 70 "cog.l"
{ return('&'); }
	YY_BREAK
case 40:
# line 71 "cog.l"
{ return('!'); }
	YY_BREAK
case 41:
# line 72 "cog.l"
{ return('~'); }
	YY_BREAK
case 42:
# line 73 "cog.l"
{ return('-'); }
	YY_BREAK
case 43:
# line 74 "cog.l"
{ return('+'); }
	YY_BREAK
case 44:
# line 75 "cog.l"
{ return('*'); }
	YY_BREAK
case 45:
# line 76 "cog.l"
{ /* comment */ }
	YY_BREAK
case 46:
# line 77 "cog.l"
{ /* comment */ }
	YY_BREAK
case 47:
# line 78 "cog.l"
{ return('/'); }
	YY_BREAK
case 48:
# line 79 "cog.l"
{ return('%'); }
	YY_BREAK
case 49:
# line 80 "cog.l"
{ return('<'); }
	YY_BREAK
case 50:
# line 81 "cog.l"
{ return('>'); }
	YY_BREAK
case 51:
# line 82 "cog.l"
{ return('^'); }
	YY_BREAK
case 52:
# line 83 "cog.l"
{ return('|'); }
	YY_BREAK
case 53:
# line 85 "cog.l"
{ yacc_linenum++; }
	YY_BREAK
case 54:
# line 86 "cog.l"
{ }
	YY_BREAK
case 55:
# line 87 "cog.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 56:
# line 89 "cog.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		jk_printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    /*register*/ YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    /*register*/ YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    /*register*/ int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    /*register*/ yy_state_type yy_current_state;
    /*register*/ YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	/*register*/ YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 121 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( /*register*/ yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
/*register*/ yy_state_type yy_current_state;
#endif

    {
    /*register*/ int yy_is_jam;
    /*register*/ YY_CHAR *yy_cp = yy_c_buf_p;

    /*register*/ YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 121 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 120);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, /*register*/ YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
/*register*/ YY_CHAR *yy_bp;
#endif

    {
    /*register*/ YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	/*register*/ int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	/*register*/ YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	/*register*/ YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = (stdFile_t)yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) _malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) _malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    _free( (char *) b->yy_ch_buf );
    _free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 89 "cog.l"

